### ISSUE TITLE
Clicking on the BlocklyProp Developer text disappears the block menu

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#10]
With a project loaded on the editor canvas, clicking on the 'BlocklyProp Developer' text does not redirect to the home page. It does, however, refresh the editor canvas with the current project and hides the left blocks menu as seen in the image below.

The expected behavior is the browser will be redirected to the home page.

![2019-07-10_14-27-41](https://user-images.githubusercontent.com/8442260/61006599-92940a80-a31f-11e9-8e89-dbfee5b05b6e.png)

**Comment by MatzElectronics** [comment]
Possibly related to #13

**Comment by pjewald** [comment]
The navigation error has been corrected in PR #14. 

There remains an intermittent issue where the blocks menu disappears when the project page is refreshed. This also seems to happen randomly if one navigates off of the page, then uses the browser's Back button to return to the editor page.

**Comment by zfi** [comment]
Further testing reveals that when the menu fails to appear after loading a new project, resizing the browser window in either direction will refresh the menu and make it visible. This is happening after the latest update to add a 100ms delay to wait for the DOM to finish loading.

**Comment by PropGit** [comment]
Isn't there an event to hook into to find out when the DOM is finished loading?  I would naturally try OnLoad, but there's reported issues with that.  DOMContentLoaded may work very well now.  There's also a readystatechange option, but [this StackOverflow](https://stackoverflow.com/questions/11936816/execute-function-after-complete-page-load) was back in 2013... I'd think DOMContentLoaded is the best option now.

**Comment by pjewald** [comment]
This issue appears to have been corrected by PR [parallaxinc/BlocklyProp-cdn #149](https://github.com/parallaxinc/BlocklyProp-cdn/pull/149).
