### ISSUE TITLE
Loading error persists and prevents any more uploads

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#101]
To replicate:

Try loading a program to an Activity Board that is off (the USB chip is still recognized), let it fail.
Turn on the Activity Board and try loading again.  The previous error is still there and does not clear.

**Comment by PropGit** [comment]
Just tried with BP Client v0.7.5 and BP Launcher v0.9.8 on Windows.  Can't replicate.  Maybe there is a platform influence? (That's hard to imagine).

### With BP Client
![image](https://user-images.githubusercontent.com/1266318/65358244-efc4fb80-dbad-11e9-925a-0edf7937478e.png)
![image](https://user-images.githubusercontent.com/1266318/65358252-f489af80-dbad-11e9-8207-c4d68ead8359.png)

### With BP Launcher
![image](https://user-images.githubusercontent.com/1266318/65358258-fb182700-dbad-11e9-8232-60699d5d00ad.png)
![image](https://user-images.githubusercontent.com/1266318/65358264-fce1ea80-dbad-11e9-889e-c8c601b14a52.png)

**Comment by zfi** [comment]
Let's get some details on the code base. What version of the app are you running @MatzElectronics ? Please pull code for 1.3.494 and retest.

**Comment by MatzElectronics** [comment]
This was on the solo production site.

**Comment by zfi** [comment]
The Solo site has been on versions 1.3.491, 1.3.493, and 1.3.494 in the past 4 hours. 

@PropGit, what version are you testing against?

**Comment by MatzElectronics** [comment]
Ugh - maybe a false alarm.  Using BPC on Mac.  Killed and restarted the BPC, now everything is working okay.

**Comment by zfi** [comment]
I'll take that. Do you have a current copy of the Launcher? We need to start dog-fooding that app.

**Comment by MatzElectronics** [comment]
I'm nearly 100% on a Mac, so waiting for that version :)

**Comment by pjewald** [comment]
Please check your email. @PropGit sent it to a group of us on 9/12.

**Comment by zfi** [comment]
@MatzElectronics is this still an open concern?

**Comment by MatzElectronics** [comment]
No, this can be closed.
