### ISSUE TITLE
Projects containing array blocks generate error when loading

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#103]
Loading a project that contains any array_fill blocks generates an error in the blockly core

![image](https://user-images.githubusercontent.com/8442260/65721020-124b8e80-e05e-11e9-8305-b8b15d92bd99.png)

```
Cannot set the dropdown's value to an unavailable option. Block type: array_fill, Field name: VAR, Value: list
```

The error appears to happen when code in propc.js attempts to update a block with a variable name 'list' and fails because the default array block does not exist.

**Comment by zfi** [comment]
Verified that adding an array with the default 'list' name causes the error to cease.

**Comment by zfi** [comment]
Further testing reveals that this issue occurs when dragging the blocks as well as when opening a project. The code appears to generate a third, default array_fill block with a default 'list' name when dragging the two blocks in the sample submitted above. 

A call to the array_init.init is what appears to be creating the temporay, extra block.

```
            .appendField(                   // create a new FieldTextInput object
                new Blockly.FieldTextInput(
                    'list',             // Default variable name
                    function (a) {      // field content validation
                        a = a.replace(/ /g, '_').replace(/[^a-zA-Z0-9_]/g, '');

                        // Set the new variable name (in a) for the array
                        this.sourceBlock_.sendArrayVal(
                            this.sourceBlock_.getFieldValue('VAR'),
                            a);

                        return a;
                    }),
                'VAR')
```
The array_fill.init is calling Blockly.Blocks['array_get'].updateArrayMenu without the old and new variable names, so I'm not sure if this is actually triggering the error.  UpdateArrayMenu appears to be responsible for populating the drop-down variable name selector in the array_fill block.

**Comment by zfi** [comment]
To test

    Set up at least 2 array init blocks with different names
    add at least 1 of each of the other types of array blocks. Ensure you can select between the available array variable names.
    change one of the names in one of the array init blocks, make sure the changes are mirroring on other array blocks using that variable name
    save and reload, ensure that all blocks re-render correctly.

**Comment by zfi** [comment]
When I add an array fill block, the dropdown for the variable defaults to 'list'. And there are no other options in the dropdown.


![Screen Shot 2019-10-16 at 3 17 31 PM](https://user-images.githubusercontent.com/8442260/66963257-1a2c9c00-f028-11e9-8edf-a754077a9f67.png)

![Screen Shot 2019-10-16 at 3 19 28 PM](https://user-images.githubusercontent.com/8442260/66963365-5fe96480-f028-11e9-9e2e-d366dbf0c03b.png)

**Comment by zfi** [comment]
Another test on a different browser (Firefox). Same result. The new code is not picking up the new array names.

![Screen Shot 2019-10-16 at 3 22 53 PM](https://user-images.githubusercontent.com/8442260/66963626-f9187b00-f028-11e9-8877-c6b4a4484dd3.png)

**Comment by pjewald** [comment]
Verified that this issue has been resolved.
Closing.
