### ISSUE TITLE
Note: User defined code block's mini code editor disappears in Chrome Browser on Android Phone

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#105]
I'm only posting a note about this because we noticed it at a lunch meeting.  It's not a show stopper by any means since the Android phones are not on the supported devices list.  

OS: Andriod 5.0
Chrome version: 77.0.3865.92

1. Open Chrome on Android phone
2. Set up a project (I named it Test with Activity Board is the board type)
3. Place a user defined code block
4. Click the main code menu option.  In Chrome on my PC, this opens a mini editor that stays open until you click outside of it.  In the phone, it only opens for a fraction of a second before it closes again.

**Comment by zfi** [comment]
@AndyLindsay, is this issue limited to the Android device?

**Comment by AndyLindsay** [comment]
The only two systems that I have used this feature on are: Windows 10 with
Chrome (issue is not evident), and the Android phone's Chrome (issue is
evident).  I'll keep an eye open and post here if I find any others.
