### ISSUE TITLE
Badge LED set state provides incorrect argument by default

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#107]
Dragging and dropping this block:
![image](https://user-images.githubusercontent.com/1266318/66615201-920a4a80-eb80-11e9-90b0-e04152dcaeb0.png)

Generates this code:
```
led(0, high);
```

which causes this error
> Compile... Succeeded.single.c: In function 'main':
single.c:22:3: warning: passing argument 2 of 'led' makes integer from pointer without a cast [enabled by default]
/opt/parallax/simple-libraries/Learn/Simple Libraries/Social/libbadgetools/badgetools.h:275:6: note: expected 'int' but argument is of type 'void (*)(int)'
undefined

But changing the __state__ from *high* to *low*, then back to *high*, generates the correct argument:
```
led(0, 1);
```
and compiles successfully.

**Comment by pjewald** [comment]
This issues is verified to be working now. Closing the issue.
