### ISSUE TITLE
Project description, created/modified timestamps are not persisted to SVG file

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#11]
The project description is missing when saving the current project to an SVG file. 

Steps to reproduce the error.
*  Open or create a project.
*  Edit project details and then enter or alter the text in the project details textarea.
*  Save the project to disk.
* Open the resulting SVG file and search for the text description. The text is not found.

**Comment by MatzElectronics** [comment]
Creation and Last Modified timestamps are not persisted either, and none of them are character-escaped properly, so I'll address each in this fix.

**Comment by MatzElectronics** [comment]
Since files saved prior to this future fix do not contain that info, there is no way for it to be known, and that will have to be accounted for in the fix as well.

**Comment by zfi** [comment]
Does this issue also affect the legacy BlocklyProp system or is this just an offline issue? Not a problem if it's the latter.

**Comment by MatzElectronics** [comment]
It's in the CDN, but under an `isOffline` conditional.  The online editor assumes you've created a project already, and are simply "importing" blocks, so the meta data for the project doesn't apply in the online system.
