### ISSUE TITLE
Load/Open projects without reloading the page

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#110]
Current behavior sets up and loads the toolbox when the page is loaded, and provides no mechanism for reloading the toolbox.  When opening a project (or starting a new one), the project is saved into localStorage, then the page is reloaded and the project is loaded from localStorage.  This process is overly complex and has caused a number of issues recently.

**Comment by MatzElectronics** [comment]
Additionally, this will likely involve removing the remining uses of the `isOffline` flag.

**Comment by MatzElectronics** [comment]
When completing this issue - please refer to minor bugs brought up in #97 
They should be addresses as part of this refactor.

**Comment by zfi** [comment]
@MatzElectronics, has this issue been resolved? I feel like we sort of backed into solving it as part of the work on other related issues.

**Comment by MatzElectronics** [comment]
No. as long as we are using re-directs (window.location.href = ...) then we
aren't there.  I've been researching the toolbox and how it can be
reloaded, and that was the big piece missing from my understanding before.
We should be able to reload the XML and the toolbox without a page refresh
at all - which would eliminate the need for using localStorage for anything
other than recovering from a page refresh.

**Comment by zfi** [comment]
I have been looking at the toolbox as well with an eye towards treating it as a real XML document. I do not see anything in the API that supports individual element manipulation, so that means a full reload every time we want to change something there. @MatzElectronics.hit me on Hangouts if you have time to chat. I think I have single page Solo working.

**Comment by zfi** [comment]
One solution is make page reload go away. That would make Solo close to a single page app. Eliminate the home page and we are essentially there. I would like to use React or Angular for that since they are specifically designed for this sort of thing but that might be too large a leap at this time.

**Comment by MatzElectronics** [comment]
I agree that solo should just be a single page app - the index.html page is largely unnecessary.
I also think that applying a framework like react or angular or vue is overkill - maybe I'm wrong about this, but it seems like a lot of overhead for very little, if any, gain.

The issue more immediately at hand is that we are using a page refresh to re-initialize blockly, instead of the provided methods for updating the project and toolbox's XML.  We shouldn't need to use localStorage at all (except for recovering from an accidental refresh/reload/power outage).

**Comment by PropGit** [comment]
I agree, no angular/react/vue just for this issue unless we find that we
can't effectively realize the single-page solution without it.

Respectfully,
*Jeff Martin <jmartin@parallax.com> | R&D @ Parallax Inc.
<https://www.parallax.com> | (916) 625-3002 | BlocklyProp
<http://blockly.parallax.com> | Learn More... <https://learn.parallax.com>*

**Comment by pjewald** [comment]
I believe that the original issue has been addressed as of the latest release to SoloCup, v1.5.0-b6. The editor page is now fully self-contained and no longer requires redirects to transition between projects.
