### ISSUE TITLE
String Variable Length block is broken

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#111]
The number block dynamic (out-of-range) warnings are populated using hidden fields on the inputs of blocks that the number block can be attached to.  This then requires us to use an override of a core function to prevent those hidden fields from showing when blocks are collapsed.

I am adding an issue to google/blockly: [google/blockly/issues/3223](https://github.com/google/blockly/issues/3223)

Additionally, the current code creates a lot of overhead, affecting the performance of BlocklyProp overall.

**Comment by MatzElectronics** [comment]
There is still a single use of hidden fields now, but hidden fields are used by other blocks, and as whole, should be removed.  I'm creating a separate issue for that.

**Comment by MatzElectronics** [comment]
There are some major issues with the `string_var_length` block.  Some of it seems to be incompatibility with the newer core, other parts seem to stem from poor design when I didn't know better.

**Comment by zfi** [comment]
Details?

**Comment by MatzElectronics** [comment]
When trying to mutate it, i'm getting this one, which I believe is related to the 'item' default variable:
![image](https://user-images.githubusercontent.com/19737272/68549236-fb14f600-03aa-11ea-872d-897e91e7c9a5.png)

Also, when loading projects that contain it (Jeff's 2075 project), it's not rendering the block correctly - his xml indicates that there is a variable in the block, but when the project is opened, it's reverted to defaults.

**Comment by PropGit** [comment]
Here's the block I have in that project:
![image](https://user-images.githubusercontent.com/1266318/68592009-ef770d00-0446-11ea-9baf-1db20467d4b1.png)

**Comment by zfi** [comment]
This appears to still be broken. When the named constant mutator is dragged over to the right-hand side, a dropdown appears over the mutator icon with the work 'item' in it. 

<img width="428" alt="Screen Shot 2019-11-15 at 2 54 34 PM" src="https://user-images.githubusercontent.com/8442260/68981366-f5a71980-07b7-11ea-8840-17b89b3957cb.png">

```
blockly_compressed.js:1430 Uncaught TypeError: Cannot set property 'nodeValue' of undefined
    at Blockly.FieldLabel.Blockly.Field.render_ (blockly_compressed.js:1430)
    at Blockly.FieldLabel.Blockly.Field.getSize (blockly_compressed.js:1434)
    at Blockly.BlockSvg.renderCompute_ (blockly_compressed.js:1571)
    at Blockly.BlockSvg.render (blockly_compressed.js:1566)
    at Blockly.BlockDragger.endBlockDrag (blockly_compressed.js:1154)
    at Blockly.TouchGesture.Blockly.Gesture.handleUp (blockly_compressed.js:1205)
    at Blockly.TouchGesture.handleUp (blockly_compressed.js:1254)
    at HTMLDocument.h (blockly_compressed.js:1841)
```

**Comment by MatzElectronics** [comment]
Yes, that's the one I referred to, but I was waiting to work on it until assigned to.

**Comment by zfi** [comment]
Also seeing this when I try to right-click on the block or try to grab it to move it.

```
blockly_compressed.js:1391 Tried to start the same gesture twice.
Blockly.WorkspaceSvg.getGesture @ blockly_compressed.js:1391
Blockly.BlockSvg.onMouseDown_ @ blockly_compressed.js:1532
h @ blockly_compressed.js:1841
blockly_compressed.js:1391 Tried to start the same gesture twice.
Blockly.WorkspaceSvg.getGesture @ blockly_compressed.js:1391
Blockly.WorkspaceSvg.onMouseDown_ @ blockly_compressed.js:1359
h @ blockly_compressed.js:1841
blockly_compressed.js:1205 Trying to end a gesture recursively.
```

**Comment by MatzElectronics** [comment]
This one is ugly.  It took forever to diagnose because the stack trace was not helpful at all.  The conclusion: there is a bug in the blockly core. Ugh.

All of these blocks are affected:
![image](https://user-images.githubusercontent.com/19737272/69314856-00174800-0bea-11ea-8467-b160d8f090d3.png)

It turns out that the variable field subject to mutation fails when a block's mutator is open.

I'll try and replicate the bug in the blockly playground to confirm that the bug is in fact in the blockly core, and then I'll submit an issue in the google/blockly repo.

There is a workaround that seems solid enough - when the mutator is open, the variable fields are removed and replaced with a text label placeholder.  when the mutator is closed, the variable fields are restored.  This approach does have two of drawbacks:
 - If the project is saved when the mutator is open, the variable fields are not captured.  
  - - To work around this, the save (download) function can be is preceded by a function that scans through all of the blocks and closes any open mutators.
 - There is a visual difference is appearance, and variable fields are frozen when the mutator is open, unlike other field types:
![image](https://user-images.githubusercontent.com/19737272/69315372-36a19280-0beb-11ea-9d95-471294db0cd0.png)

**Comment by MatzElectronics** [comment]
Bug submitted to google/blockly: [blockly/#3458](https://github.com/google/blockly/issues/3458)

**Comment by MatzElectronics** [comment]
@BeksOmega 's fix for the issue in blockly appears to solve this for us (Yay!!!).  I'll implement her patches as overrides in propc.js and continue working on this issue.  I'll post and edit the PR when I finish.

**Comment by zfi** [comment]
The constant block appears to accept "- bbbbb" as a legal value. Shall I log this as a new issue?

![Screen Shot 2019-11-25 at 2 57 38 PM](https://user-images.githubusercontent.com/8442260/69585235-f5ff9b80-0f93-11ea-8cc7-95b18029481d.png)


```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#define MY_MYVALUE - bbbb



// ------ Main Program ------
int main() {


}
```

**Comment by MatzElectronics** [comment]
Yes please.

**Comment by zfi** [comment]
Also discovered that one can create a constant with a negative value and apply that to the string_variable_set block and the block does not complain. However, the compiler does protest when the code is submitted.

![Screen Shot 2019-11-25 at 3 14 45 PM](https://user-images.githubusercontent.com/8442260/69586100-5a235f00-0f96-11ea-863b-9bb2d7c06d3d.png)

```
/* SERIAL_TERMINAL USED */


// ------ Libraries and Definitions ------
#include "simpletools.h"
#define MY_CONSTANT_1 10
#define MY_CONSTANT_2 4
#define MY_CONSTANT_3 - 5

// ------ Global Variables and Objects ------
int alpha;
int mu;
int omega;
char beta[MY_CONSTANT_3 + 1];



// ------ Main Program ------
int main() {

  strcpy(beta, "Hello"); // Save string into variable beta.
  print(beta);

  alpha;

  mu;

  omega;

}
```

Results in: 



```
Compile... Failed!

-------- compiler messages --------
Included libraries: simpletools
single.c:14:6: error: size of array 'beta' is negative
undefined
```

**Comment by zfi** [comment]
Here is another example that is not going to do what the user expects. Here, we are setting the size of beta to 4 characters and then assigning "Hello World" to it. The compiler does not complain but this is going to create a silent run time failure when we overrun the buffer.

![Screen Shot 2019-11-25 at 3 19 34 PM](https://user-images.githubusercontent.com/8442260/69586314-0feead80-0f97-11ea-8f45-6bb4267789a8.png)

```
/* SERIAL_TERMINAL USED */


// ------ Libraries and Definitions ------
#include "simpletools.h"
#define MY_CONSTANT_1 10
#define MY_CONSTANT_2 4
#define MY_CONSTANT_3 - 5

// ------ Global Variables and Objects ------
char beta[MY_CONSTANT_2 + 1];
int alpha;



// ------ Main Program ------
int main() {

  strcpy(beta, "Hello World"); // Save string into variable beta.
  print(beta);
}
```

**Comment by MatzElectronics** [comment]
Thank you, looks like we need to add some checks into this.

Another thing you can do with the constant defines is put a pin out of
range.any of the sensor blocks allow you to used a named constant as the
pin.

This particular block was targeted for "power users", so please weigh the
priority of this before we spend time on putting checks in place.  Doind so
isn't trivial, and would likely require some time.

**Comment by zfi** [comment]
Alright, we'll come back to these after we get through the remaining bugs on the current milestone.

**Comment by zfi** [comment]
Pulling this from milestone v1.4.0 since this is not going to get resolved in time.

**Comment by zfi** [comment]
It looks like the original issue has been resolved but requires testing.
