### ISSUE TITLE
Refactor blocks that use hidden fields

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#113]
After discussion with Sam on the Google Core team, we should not be using `.setVisible()` on fields - it's not a public method.  Some research is required, but I believe we can accomplish the intended effect by adding and deleting inputs, which is what we have done on many of our blocks.  Currently, it appears that 10 of our blocks are using this in their mutators.

**Comment by MatzElectronics** [comment]
Can this be closed now?  Custom code block is a separate issue.

**Comment by pjewald** [comment]
The PR contains what changes were required to accomplish this and a list of blocks that require testing. We're missing a discussion on what is replacing the calls to .setVisible().

@MatzElectronics - I think you may have tested the blocks listed in the PR. Can you verify that?

**Comment by MatzElectronics** [comment]
Instead of using `.setVisible()`, the blocks should be deleting (`.removeInput()`) and then rebuilding inputs.  This causes re-renders and correctly displays the blocks.

Yes, everything was tested and has passed.

**Comment by pjewald** [comment]
Closing this issue.
