### ISSUE TITLE
Update New Project dialog

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#115]
Update the New Project dialog to remove the project name and project description fields. 

**Discussion**
The only data required to create a project are the project name. The project name will be defaulted to 'default_project' and the project description will remain empty.. The dialog should only present an option to select the project's Board Type.

**Comment by AndyLindsay** [comment]
Looks good.  I would suggest making the default name 'BlocklyProp Program'.

**Comment by MatzElectronics** [comment]
I think we have an opportunity to do some nice UI work here.  Just a set of buttons arranged in a grid with a picture of each type of device.  Click and go.

**Comment by zfi** [comment]
This appears to be resolved.
Closing the issue.
