### ISSUE TITLE
Remove Download Project - Filename ...Confirm step from Save

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#118]
After #106 makes the project name modifiable from within the editor, remove the Download Project - Filename...Confirm step that follows a click the the Save button.  When Save is clicked in the editor, the download filename will match whatever the project name has been set to.

**Comment by zfi** [comment]
@AndyLindsay Could you provide a screenshot of the "Download Project..." bit. I'm not sure uf you are referring to something that used to be in the hamburger menu of perhaps a dialog box. I think the current UI might be a little different than when this issue was created.

**Comment by AndyLindsay** [comment]
For clarification, the dialog below is unnecessary.  The user has already chosen the name in the upper-right editable project name field.  As soon as they click the Save button (also in the upper-right), they can reasonably expect a download with a filename that matches the project name.   

![Download Proiject Filename](https://user-images.githubusercontent.com/11575415/68997393-e200bf00-085a-11ea-931c-67430b0c0746.png)

**Comment by zfi** [comment]
PR #170 included an update to address this issue. However, when I click the Save button in the editor UI, I still get a  **Save As** dialog that looks nothing like the modal in the above example with a Chrome browser. What am I missing?

![Screen Shot 2019-11-25 at 4 58 14 PM](https://user-images.githubusercontent.com/8442260/69590591-d7ee6700-0fa4-11ea-899d-8dab4da6bc4a.png)

**Comment by MatzElectronics** [comment]
That box is a chrome dialog, not one of our own, so I don't think we have
any control over it - Do you always get it when you download a file?
https://stackoverflow.com/questions/8863940/how-to-force-chrome-display-a-save-as-dialog-when-i-click-a-download-link

**Comment by zfi** [comment]
I always see this dialog when I **Save** my project. Is that the same thing as downloading? I am just trying to verify the behavior requested in this issue. I "think" it's gone, but I'm not sure.

**Comment by MatzElectronics** [comment]
Yes - since this is in a browser, the file is effectively "downloaded" - for all intents and purposes, it's the same mechanism.

**Comment by MatzElectronics** [comment]
Yes, there was an additional step on our side that gave the opportunity to rename the file, and that's what was deleted.  It would have been a bootbox that looked exactly like what @AndyLindsay showed above.

**Comment by zfi** [comment]
Disabling the **Ask where to save each file before downloading ** in Chrome removed the dialog I reported earlier and the project is saved as described in this request. So that's good. 

We do need to document the alternate user experience for those users who have this setting enabled.

**Comment by zfi** [comment]
Verified that this is now working as expected. 
Closing this issue.
