### ISSUE TITLE
Improve/Fix code fields in the custom code block

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#128]
Drastic changes and improvements to the custom field API in the blockly core have:
1. broken the custom code block
2. provide better mechanisms to accomplish what the custom code block is trying to do

The block needs:
- The custom FieldCode type to be redefined.  
  - See [Beka Westberg's Custom Map Field](https://github.com/BeksOmega/BlocklySummit2019-Fields/blob/master/map/field_map.js) as a starting point/example
- Currently, the block hides fields.  As in #113, this needs to be refactored to instead save->delete->recreate->repopulate them instead.

**Comment by zfi** [comment]
Is this in reference to v2 or v3 Blockly core? We should discuss deferring this issue until we start working against the v3 core.

**Comment by MatzElectronics** [comment]
They are currently broken in solo...so v2 I think.

**Comment by pjewald** [comment]
What exactly is broken that this issue is supposed to address? 

I would prefer that we put this in a feature branch so it can be tested in isolation. Dropping large code changes into the develop branch leaves me with few options if the code breaks things.

**Comment by MatzElectronics** [comment]
The core update that ent into solo broke the custom code block -
specifically the custom field type (code).
The block appears to work until you try to edit a code field, then it locks
everything up.

This fix addresses what broke by creating a newer, better custom field type
and by refactoring to remove hidden fields (as was done with lots of other
blocks).

If it was purely to improve it, I would have used a feature branch, but the
urgency and bug branch is because it's not currently function, and is used
often enough both for power users and as a tech support and development
option that it needed more urgent attention.

**Comment by zfi** [comment]
Our track record on merging large changes that actually work is not good. There is a conflict in the PR that needs to be resolved. I will accept the PR once that is fixed. Then we get to test the results for the next few days.

**Comment by MatzElectronics** [comment]
In testing, look specifically for opening files that already had a custom code block - although I had a few files to test with on my end, I think that specific piece needs a close look/verification - the method I had to use to keep the block backward compatible was a bit unorthodox...

**Comment by zfi** [comment]
Do you need test project that already have the custom code block? We could do some dumpster diving in the database on Demo to find such projects.

**Comment by MatzElectronics** [comment]
I did some testing with the batch of files that Jeff sent us, and I worked
through everything on those, but yes, some diving would be good, especially
for custom code blocks that have a lot of c code in them.

**Comment by zfi** [comment]
Where does one find the custom code block in the toolbox? I want to verify that it is working but not being successful at finding the correct combination of board type and toolbox.

**Comment by MatzElectronics** [comment]
I think all board types but scribbler.  It's in the system menu, labeled
user defined code

**Comment by VonSzarvas** [comment]
I'm hitting an issue that seems the same as this issue, so attaching screenshot to confirm it's still an issue from Win10 + Chrome78. 

issue: Not able to add the inline code via user-defined-code block; text box appears top-left, and the user-defined-code block gets a yellow edge and moves with the mouse. Can't do anything except refresh the browser page to recover from this.
![2019-11-28 15_11_29-BlocklyProp Solo](https://user-images.githubusercontent.com/11635798/69813334-47a56180-11f2-11ea-8721-fa8a0975a9fb.png)

**Comment by pjewald** [comment]
This is likely addressed in the upcoming 1.3.505 release. I tried to reproduce the error but all of the editor boxes are well behaved in the dev environment.

<img width="509" alt="Screen Shot 2019-11-28 at 8 28 07 AM" src="https://user-images.githubusercontent.com/11216070/69821615-0a70ad80-11b9-11ea-9a46-23af99f58715.png">

**Comment by zfi** [comment]
Confirmed that the block is working as expected as of 1.3.511.
Closing the issue.
