### ISSUE TITLE
Block toolbox doesn't render when the window is a certain width

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#13]
The block toolbox, trash can, and zoom buttons don't appear if the window is ~920px wide when a new project is loaded.  Not sure if this is the only cause or even what is causing it.  Simply resizing the window makes it appear, so it may be possible to force a 'resize' event once the DOM is rendered to workaround this issue.
 jQuery provides a method for this:
https://api.jquery.com/resize/

**Comment by MatzElectronics** [comment]
BTW this does not appear to be caused by a javascript error - this may be in the site's CSS.  No console errors are shown, and I believe everything else is functional - i was even able to paste a bunch of blocks in the XML using the XML tab and have the blocks appear and work normally (dragging was clunky)

**Comment by zfi** [comment]
SL is reporting that this issue still exists after the latest update.

About 5 times now, I create a new project, and my first click to the Blocks menu (on Control) makes the entire left-side blocks menu pane dissapear. I was going to do a screencap, and accidentally re-sized the window, dragging it smaller. This made the menu reappear.  Weird!

**Comment by MatzElectronics** [comment]
Tracking this with [BlocklyProp-cdn#156](https://github.com/parallaxinc/BlocklyProp-cdn/issues/156)

**Comment by PropGit** [comment]
I confirm - for me, every time I have a new project and click on an item in the toolbar (usually Control is what I'm clicking first), it completely disappears.  Then I click refresh, it reappears and usually stays visible the next time I click an item within it.

**Comment by zfi** [comment]
This appears to work correctly in v1.3.463. Can @MatzElectronics or @PropGit  test this again in their dev environment?

**Comment by PropGit** [comment]
I don't currently have the proper dev box working.  Need to meet with you next week to resolve that.

**Comment by MatzElectronics** [comment]
Working ok on my end.
