### ISSUE TITLE
Solo is unable to import files created from Bulk Project Downloads

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#130]
Files created from a bulk project export feature on the blockly.parallax.com site have a .svge file extension. An attempt to load any project with this extension fails and leaves the Open Project dialog open and nonoperational.

**Comment by zfi** [comment]
The file loader code is expecting an 'image/svg+xml' mime type before processing the project file. Added code to identify the special file extension and permit them to be loaded in the same way as traditional .svg files are loaded.

**Comment by zfi** [comment]
PR #131 includes code to address this issue. Can someone please test importing .svge files and report back?

**Comment by PropGit** [comment]
Yes, this works now.
