### ISSUE TITLE
Refactor deprecated function call Blockly.bindEvent_()

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#133]
The Blockly.bindEvent_() method is deprecated in v2 blockly core and removed in v3 core. Refactor code to replace the depricated  bindEvent_() call. 
```
        // Reinstate key bindings from block workspace if this is not a code-only project.
        if (Blockly.codeOnlyKeybind === true) {
            // TODO: Need to replace bindEvent_ call with somethign that is not deprecated
-->>    Blockly.bindEvent_(document, 'keydown', null, Blockly.onKeyDown_);
            Blockly.codeOnlyKeybind = false;
        }

```

**Comment by MatzElectronics** [comment]
We should be able to remove this entirely.  I'll have to explain it to you next time we do a hangouts - but the gist is that is is only for prop-c code editing, and since we are planning on refactoring the whole startup/init process anyway, there is an opportunity to remove this altogether.

**Comment by pjewald** [comment]
Verified.
Closing.

**Comment by zfi** [comment]
Reopening this issue.
PR #168 introduced a breaking change that needs to be corrected. In editor.js beginning at line 867, there is a new code fragment that causes initToolBox() to fail at line 1603. I believe this is happening because the code within setupWorkspace() is destroying the contents of the Blockly object. The code that is failing expects that the Blockly object is already populated. We can't have it both ways.

New code:
```
   } else {
        initToolbox(projectData.board, []);
        $('#online-help').attr('href', 'https://learn.parallax.com/ab-blocks');
        // Create UI block content from project details
        renderContent('blocks');
    }
```

Failure:
```
    } else {
==>     for (var f = 0; f < Blockly.Css.CONTENT.length; f++) {
            Blockly.Css.CONTENT[f] = Blockly.Css.CONTENT[f].replace(/Arial, /g, '').replace(/sans-serif;/g, "Arimo, sans-serif;");
        }
    }
```

```
editor.js:1603 Uncaught TypeError: Cannot read property 'length' of null
    at initToolbox (editor.js:1603)
    at setupWorkspace (editor.js:868)
    at HTMLDivElement.<anonymous> (modals.js:196)
    at HTMLDivElement.dispatch (jquery-1.11.3.min.js:26)
    at HTMLDivElement.r.handle (jquery-1.11.3.min.js:26)
    at Object.trigger (jquery-1.11.3.min.js:26)
    at HTMLDivElement.<anonymous> (jquery-1.11.3.min.js:26)
    at Function.each (jquery-1.11.3.min.js:24)
    at m.fn.init.each (jquery-1.11.3.min.js:24)
    at m.fn.init.trigger (jquery-1.11.3.min.js:26)
```

**Comment by MatzElectronics** [comment]
How can I replicate the error?  I'm not able to trigger the bug you're seeing...

**Comment by zfi** [comment]
Open the developer console and follow these steps to reproduce the error:
** Load any project
** Click on the 'New' button.
** Click 'Cancel' on the New Project dialog.

SetupWorkspace() is blowing up the Blockly object, then calling InitToolbox(). Code inside InitToolbox is fiddling with font families and fails because the Blockly.Css.Content object is null;

I'm going to add a test in the code to ensure that we don't try to reference something that we know isn't there.

**Comment by zfi** [comment]
This is no longer an issue in 1.3.512. The procedure outlined above now appears to work correctly.
Closing this issue.
