### ISSUE TITLE
Replace Open button alert window with a bootstrap modal 

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#136]
Address issue raised in #97 

The Open button on the editor page is invoking an alert box when it detects that the current project has been modified and not yet saved to disk. The button handler should instead invoke a bootstrap modal dialog consistent with the modal used by the New button.

**Comment by MatzElectronics** [comment]
Use one of the bootbox modules in utils.js - that's what they are for :)

**Comment by zfi** [comment]
So, that makes me wonder why we are not using them everywhere. They seem to be easier to use and far more predictable to use. 

fwiw, I looked at the jQuery modal package and it appears to be either poorly maintained of not at all. We can cover that in another issue.

**Comment by zfi** [comment]
The browser dialog has been replaced with a modal dialog as of 1.3.512.
Closing this issue.
