### ISSUE TITLE
Project name to saved file name case changes and character substitutions

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#147]
Given a project name of: Abc Defg * 1234

The saved filename becomes: abc_defg___1234

The file download behavior I am familiar with in other systems preserves capitalization and spaces and only removes OS reserved characters, like the *.  Could we do that here too?

**Comment by zfi** [comment]
This is a continuation of issue #106.

**Comment by zfi** [comment]
> Given a project name of: Abc Defg * 1234
> 
> The saved filename becomes: abc_defg___1234
> 
> The file download behavior I am familiar with in other systems preserves capitalization and spaces and only removes OS reserved characters, like the *. Could we do that here too?
