### ISSUE TITLE
Attempts to drag SD Card read/write block disables dragging functionality

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/solo#157]
Attempting to drag the "SD file" block that contains the read/write option causes block dragging functionality to stop working, until the page is reloaded.  This is true whether the block is already in the project or being dragged into it.  It appears to occur for all board types, when the block is available, and in all web browsers.

**Comment by pjewald** [comment]
This seems to happen on any SD block except the Init block.

<img width="574" alt="Screen Shot 2019-11-13 at 2 03 09 PM" src="https://user-images.githubusercontent.com/11216070/68808316-56025380-061e-11ea-87b0-b73b437c95c5.png">

**Comment by zfi** [comment]
The updated code in pr #160 appears to have corrected the reported issue. This update will appear in version 1.3.505.
