### ISSUE TITLE
Adjust UI elements (upload and download) to open, import, and save

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#16]
This includes:
Remove the "append" button in the modal when opening a project
Change the "replace" to "open" in the modal when opening a project
Change the title from "Upload" to "Open" or "Import" (depending on state)

**Comment by PropGit** [comment]
@MatzElectronics - Just making sure; there will be an Open and an Import mode of this operation (as indicated above) and the Open mode will have a single button "Open," and the Import mode will have two buttons "Replace" and "Append?"

**Comment by MatzElectronics** [comment]
That is the desired behavior, yes.

**Comment by pjewald** [comment]
Verified updated behavior. Closing the issue.
