### ISSUE TITLE
Restore experimental=true url parameter behavior

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#167]
In the original production system, if `experimental=true` was added to the URL, it enabled any blocks marked as experimental and it enabled the ability to use the PropC editor by itself.

In the course of creating solo, we've inadvertently disconnected these hooks/triggers.

**Comment by zfi** [comment]
@MatzElectronics, how can this be tested for verification?

**Comment by MatzElectronics** [comment]
From the index page, add `?experimental=` and `blocks`, ` saveas`, and/or `volatile ` (with a `|` as a separator) to the URL.  It will pass the parameters through to the editor, where they will toggle features like additional blocks (Communicate > Parallel LCD is one example), a different save as function (only really applies to production, not solo currently), and more optimizable generated code (adding volatile to variables used across multiple cogs).

**Comment by zfi** [comment]
Found an error in the Open Project handler that was truncating the querystring after the file was opened.

**Comment by zfi** [comment]
This appears to be working without interfering with the core system.
Closing this issue.
