### ISSUE TITLE
Triangle Warnings when duplicating Array Set Element 

### ISSUE THREAD

**Issue by francisbauer** [parallaxinc/solo#172]
When I duplicate an existing Array Set Element block, it shows a triangle warning indicating that the previous named array is not initialized (see attached image).  A lot of times this is "list", the default array name, but it also can be an array name of a previous array.  No matter what I change the array names to either in the initialize block or select a different name in the Array Set Element block, the triangle warning persists and only changes the name of the array name that it is complaining about.
Fortunately this "bug" is only a visual annoyance, since the code compiles and runs fine.

![BlocklyPropSoloBug](https://user-images.githubusercontent.com/53076503/69025132-a6f5ad00-097a-11ea-991f-c045711740fb.jpg)

**Comment by MatzElectronics** [comment]
@francisbauer Could you email me the svg file from your project? I'm at matt dot m dot matz at gmail dot com.  I'm struggling to replicate the bug you are seeing.

**Comment by zfi** [comment]
This is still a bit broken. The array fill drop down in the sample project below contains three elements, "stuff", "list", and "LED". Note that there are initialization blocks for "stuff" and "LED" but not "list". If one were to select "list" in one of the array fill blocks, the warning triangle will appear.

I understand that "list" is a default and therefore, a special case. But the array fill blocks are not handling it well.

![Screen Shot 2020-01-09 at 4 17 00 PM](https://user-images.githubusercontent.com/8442260/72115331-85ba9880-32fb-11ea-84ec-1a7dde64294e.png)


[Solo-172.svg.zip](https://github.com/parallaxinc/solo/files/4043248/Solo-172.svg.zip)

**Comment by MatzElectronics** [comment]
I'm afraid that without a near-complete overhaul, this is as good as it gets.  If we try to remove the "list" from the menu (which I tried to do when we overhauled these recently), it breaks in all kinds of fun ways.  The warning is appropriate because it's telling the user they need an init for "list" if they wish to use it.

**Comment by zfi** [comment]
I agree the warning is appropriate. If removing the 'list' item is as devastating as it appears, would it make more sense to ensure that 'list cannot be removed?

**Comment by zfi** [comment]
It appears that 'list' receives special treatment within the Blockly core. We should probably document the special treatment as a reserved word in BlocklyProp and move on.

https://groups.google.com/forum/#!topic/blockly/bTaGcvA95YE
