### ISSUE TITLE
Cannot create a new project from inside the edit pane

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#174]
Behavior described below is the same whether or not I have made any changes.

Starting from an open project: 

- Click New
- Save Project dialog opens.  It says "The current project has been modified. Click OK to discard the current changes and create a new project."  (This dialog is displayed even if I have not changed the project, even if I have not clicked inside the edit pane after opening the project). 
- Click OK.  Instead of discarding changes and creating a new project, the "Download Project - Filename: dialog appears.  
- If I click Confirm, the project is saved, but I stay in the same project - no new project is created.
- If I click Cancel, the project is not saved, and I stay in the same project - no new project is created. 
If I click the upper left icon and then click Leave, to escape the edit pane,  I can create a new project from there.

**Comment by MatzElectronics** [comment]
This appears to happen in other circumstances too.  When I tried to import blocks I ran into a similar issue.

**Comment by zfi** [comment]
This has been corrected in the 1.4.0-rc1 release.
Closing the issue.
