### ISSUE TITLE
Named constants are not working properly

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#175]
Named constants should track changes and re-populate menus on the fly.  They no longer appear to be:
![image](https://user-images.githubusercontent.com/19737272/69315710-fbec2a00-0beb-11ea-8c27-27fdd3c2f8ba.png)

I believe the fix for this will be similar to the refactor we used with the array blocks - the code for the named constants was derived from the array blocks' code, which is likely why they are now failing in a similar manner.

**Comment by MatzElectronics** [comment]
This may be fixed in #176...not seeing the issue any longer in that PR...

**Comment by zfi** [comment]
I agree that this appears to have been corrected.

I am a little concerned that the default "MYVALUE" constant appears in the list when one or more constant blocks have been declared with names other than "MYVALUE". The issue is that the MYVALUE constant does not appear to have a default value, so if it is used in the string variable set size block, the compiler fails with this message:

```
Compile... Failed!

-------- compiler messages --------
Included libraries: simpletools
single.c:11:11: error: 'MY_MYVALUE' undeclared here (not in a function)
undefined
```
This needs a resolution.

**Comment by MatzElectronics** [comment]
Okay, fair enough.  It shouldn't be too difficult to remove it from the
menu builders when they detect existing named constants.

**Comment by zfi** [comment]
I was just discussing this with @Steph-Parallax and it would actually make sense to just have a default for the MYVALUE appear in the emitted code. It appears to default to 0, so that would allow the default value to appear in the constant name drop downs and still compile.

**Comment by MatzElectronics** [comment]
Sounds good - definitely the easier approach.

**Comment by MatzElectronics** [comment]
Upon further testing, there are still some issues - especially around renaming and deleting named constant define blocks.  The solution will be to apply the same principles we used for the array blocks as stated earlier - it will just be a bit of a slog to get through them all.

I would like to de-prioritize it a bit, however (push to a later release, remove from .505 milestone).  If you're using named constants, your probably an advanced enough user to correct it when something doesn't look right.  Nothing is "show-stopper" broken...more "mildly annoying" broken in its current state.

**Comment by pjewald** [comment]
Pulling this out of the 1.4 release. This still needs attention.
