### ISSUE TITLE
Vertical scrollbar doesn't resize when tall project opened

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#178]
I don't recall having this problem before the recent update.  

When opening a large project, the vertical scrollbar doesn't resize, leaving the user unable to see rest of project (via scrollbar or mousewheel).  Dragging the project around with the mouse in the editor view does indeed work.

![image](https://user-images.githubusercontent.com/1266318/69567836-2ed94980-0f6f-11ea-9afe-5d56b4b4de10.png)

**Comment by MatzElectronics** [comment]
This feels like a core issue - blocky calculates the canvas size when it loads the project, and it doesn't look like it's being done correctly.  We should try to replicate the effect of this in a blockly playground to see if that's happening there, too.

**Comment by PropGit** [comment]
That sounds like a good theory.  Sorry, I meant to include that project.  It's attached here.


[StopLight.zip](https://github.com/parallaxinc/solo/files/3892665/StopLight.zip)

**Comment by zfi** [comment]
Coming back to this now and finding that the project is not loading successfully in 1.3.512.

**Comment by PropGit** [comment]
Uh oh.  Something is (re)broken in the parser?

**Comment by pjewald** [comment]
The project is loading and getting stored in the browser localStorage, but the code that is supposed to pick that up and load it into Blockly is just not getting executed. This appears to be a problem with async calls getting out of step. I'm still working through it.

**Comment by zfi** [comment]
Found code that was not properly clearing the localStorage after loading a project. Subsequent code detected that there was a project in the localStorage and proceeded to load it.

**Comment by zfi** [comment]
All noted issues have been addressed in v1.4.0-rc1.
Closing this issue.
