### ISSUE TITLE
Remove 3 overrides in proc.js after core has been updated to include mutator fixes.

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#179]
There are 3 overrides introduced in #111 written by the google team to patch a bug with fields in a block that mutates.  Once we are able to upgrade to a core release that contains those patches, these will need to be deleted.

They are marked with descriptive TODOs and are all in propc.js

**Comment by zfi** [comment]
@MatzElectronics can you check and see if these patches were incorporated into the Blockly core and if so, which release?

**Comment by MatzElectronics** [comment]
[Q4 2019](https://github.com/google/blockly/releases/tag/3.20200123.0) appears to contain the fix, but if we pull that in, we should do so in a feature branch and make sure other things don't blow up.

**Comment by zfi** [comment]
This was accomplished in the Solo 1.5.10 release.
Closing the ticket.
