### ISSUE TITLE
Update Solo to support TLS

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#181]
Update Solo server to support TLS (HTTPS) in addition to HTTP.

BlocklyProp Launcher uses and https protocol for the **Open Browser: BlocklyProp Solo** button.

**Comment by zfi** [comment]
An update to the Terraform configuration has been applied to the test system that provides TLS support.

**Comment by zfi** [comment]
Verified that Solo supports TLS. Note that insecure access to Solo is deprecated and will be removed in Q3, 2020.
Closing this issue.
