### ISSUE TITLE
SVG XML header causes project to be flagged as changed

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#183]
Older  projects that were created with the older v1 and v2 blockly core contained a name space designation that is different that the one provided in v3 core. This difference is detected in the checkLeave() function and causes that function to declare the project  as changed, even though the block definitions have not changed. 

Should the code ignore the name space declaration when comparing the current state of the project with the last known state? 

```
Version 1 & 2
<xml xmlns=\"http://www.w3.org/1999/xhtml\">blockly/xml\">
```
```
Version 3
<xml xmlns=\"https://developers.google.com/blockly/xml\">
```

**Comment by MatzElectronics** [comment]
I think that ignoring it is a good approach.

**Comment by zfi** [comment]
I will add a new function that compares the block section of the code data for equality. That can then be fed back to the checkLeave function, so we're not breaking anything higher up.

**Comment by zfi** [comment]
The new code to detect block changes is detecting a new issue with the **controls_repeat** block. The new core is representing the mutation element differently than projects created with the older core. This is especially true with projects that were bulk exported from the BlocklyProp production system. As a result, Solo will see these projects as "changed" immediately after they load. 

I don't see a clean resolution to this. I'll leave this here to document the issue. 

<img width="394" alt="Screen Shot 2019-11-26 at 10 42 43 PM" src="https://user-images.githubusercontent.com/8442260/69700086-73173780-109e-11ea-8c6e-cd48f3ed2192.png">

<img width="722" alt="Screen Shot 2019-11-26 at 10 40 58 PM" src="https://user-images.githubusercontent.com/8442260/69700107-81655380-109e-11ea-88a4-adcdc5e18a36.png">

**Comment by MatzElectronics** [comment]
Let's just use a setTimeout to capture the new XML 1500 ms into the project
and base everything off of that...there's no way that someone is going to
change it drastically within the first 1.5 seconds.

**Comment by MatzElectronics** [comment]
Or look for a flag in blockly that is set once everything is fully loaded,
and capture the XML at that point in time.

**Comment by zfi** [comment]
I'm not following how that would affect this issue. The project is loaded successfully. The issue here is that the core is returning a slightly revised version of the block xml when the user attempts to leave the currently loaded project, either by creating a new project or opening an existing project. We do a check to see if the project has changed since the original load or save operation. That is where this issue is detected.

**Comment by MatzElectronics** [comment]
Sorry I'm not doing a good job of explaining.   Would you be willing to
assign this one to me?

**Comment by zfi** [comment]
I think you are suggesting that we simply overwrite the initial state of the project after some short delay, thereby removing the deltas that are triggering the state change code to fire.

**Comment by MatzElectronics** [comment]
Exactly, yes.  The trick is to find the shortest possible delay, or to see
if Blockly's workspace initializer has a callback.

**Comment by zfi** [comment]
Verified that this is now working as expected.
Closing the issue.
