### ISSUE TITLE
Project code detection needs to be refactored

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#192]
* Refactor code in blocklyc.js:line 503 to replace the xml namespace string with the constant EMPTY_PROJECT_CODE_HEADER.

* Replace code that checks for a specific string length with a function that looks for the first <block> xml element in the project. This will make the code immune to any changes in the length of the xml namespace string. Use compareProjectCode() in editor.js for inspiration. 

```
   if (projectData) {
        if (!projectData['code'] || projectData['code'].length < 50) {
            projectData['code'] = '<xml xmlns="http://www.w3.org/1999/xhtml"></xml>';
        }
        if (projectData['board'] !== 'propcfile') {
            loadToolbox(projectData['code']);
        }
    }
```

**Comment by zfi** [comment]
The code in blocklyc.js:420 is still using the hard-coded XML namespace definition.

```
var propcAsBlocksXml = function () {
    let code = '<xml xmlns="http://www.w3.org/1999/xhtml">';
    code += '<block type="propc_file" id="' + generateBlockId(codePropC ? codePropC.getValue() : 'thequickbrownfoxjumpedoverthelazydog') + '" x="100" y="100">';
    code += '<field name="FILENAME">single.c</field>';
    code += '<field name="CODE">';
    [...]
```

**Comment by MatzElectronics** [comment]
I've replaced the code in blocklyc.js:420,

But throughout, we still have both
- `Project.prototype.EmptyProjectCodeHeader`
- `EMPTY_PROJECT_CODE_HEADER`

I think that we need to choose one or the other only.

**Comment by pjewald** [comment]
The Project.prototype.EmptyProjectCodeHeader is the default used by the Project class. This will get resolved as part of refactoring code to use the Project class.

**Comment by zfi** [comment]
All hard-coded XML namespace strings have been replaced with a constant.
Closing this issue.
