### ISSUE TITLE
Terminal thinks there is a connection when there is no device when using websocket client

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#200]
![image](https://user-images.githubusercontent.com/19737272/70410313-7fd34e00-1a03-11ea-8168-cc645cc222f3.png)

If you do not have a connection to a device when using the non-ws client, it will simulate the terminal and inform you that no devices are connected.  When using the websocket client, it thinks that "No devices" is a device, and tries to connect with it, which then causes a bunch of communication errors.

We can use `getComPort()` in the callback for the terminal to verify a connection, but `getComPort()` is slow because it's looking for the selected option in the menu instead of just getting the menu's value:
```
// current (slow)
var getComPort = function () {
    return $('#comPort').find(":selected").text();
};

// should be (faster)
var getComPort = function () {
    return $('#comPort').val();
};
```

We should then replace text like "Searching..." and "No devices detected." with string constants because we'll have to test for them.

**Comment by pjewald** [comment]
Where is the code

**Comment by pjewald** [comment]
Why is the web socket connection getting treated differently that the HTTP client when it comes to enumerating available ports? It seems to me that the code that is looking at the port enumeration should not be tightly coupled to the protocol used to get the enumerated list of available ports.

If we are getting the port list from a UI element, we need to change that so that the UI component is getting that data from a model that apparently does not yet exist.

**Comment by MatzElectronics** [comment]
It makes sense that it's coming from a UI element - the user has to choose which device they want to connect to.

**Comment by PropGit** [comment]
I agree that it should not be treating the symptom differently based on client-type, but it's not clear to me that it is doing so directly.  @MatzElectronics - are you saying that differences in the responses from BP Client vs BP Launcher under these conditions is causing this problem?  If so, we just need to accommodate what BP Launcher is delivering as it sounds like that hasn't been the case.

**Comment by MatzElectronics** [comment]
Correct.  The order of conditionals first checks for the type of client -
none, post, or websocket.  Then, if it's none, it behaves accordingly.  If
it's post, there is an additional condition to check for a
connected.selected device.  It behaves accordingly either way.  If the
client is websocket, there are no additional conditionals to direct it to
behave a certain way, and that's what needs to be addressed.

**Comment by zfi** [comment]
@MatzElectronics Can you list the steps to reproduce the error?

**Comment by MatzElectronics** [comment]
Steps to reproduce:

Using a websocket client, open a new project, but do not connect any devices to your computer.
Click the round blue open terminal button on the left side of the top menu bar (next to the load to eeprom button).
You should then see the terminal open and an error in the console, especially if you try typing into the terminal.

Compare this behavior to the same scenario but with the original non-websocket client.

**Comment by zfi** [comment]
The last test with the terminal window no longer fails as described. However, the dev console is reporting an error as soon as the terminal window is opened as described in the above procedure.

```
blocklypropclient.js:417 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at WebSocket.connection.onmessage (http://localhost:8082/src/blocklypropclient.js:417:30)
connection.onmessage @ blocklypropclient.js:417
```

**Comment by MatzElectronics** [comment]
That's correct.   The launcher is inconsistently encoding some messages,
hence the try/catch

**Comment by zfi** [comment]
Which try/catch? The console error message is indicating that the exception was not trapped. The only try/catch block in the source file does not capture the atob() failure. Is there another one that I am not seeing?

**Comment by MatzElectronics** [comment]
Nevermind... that's in one of the future 200x PRs

**Comment by zfi** [comment]
Closing this issue.
