### ISSUE TITLE
Secure Solo cannot reach the compiler service

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#205]
Accessing Solo via HTTPS creates an issue where the browser is unable to access the compiler service because the the compiler service is not accessible through the HTTPS protocol.

**Comment by zfi** [comment]
The browser-based code is trying to reach the compiler service on port 5001 using http when the browser is connected to the web server on port 443 using https. The solution is to update the browser code to use https on port 443 for compilation services and then have the load balancer look at the inbound URL and forward the request to the compiler service on port 5001.

This will permit the browser code to send all traffic to port 443. This also has a desired side benefit of no longer requiring users to have to open port 5001 on their firewall to perform compilations.

**Comment by PropGit** [comment]
What a great solution!

**Comment by zfi** [comment]
This has been implemented. The browser code detects the protocol used to reach the Solo server and then adjusts the port used to submit compiler jobs based on the protocol identified.
Closing this issue.
