### ISSUE TITLE
Add BlocklyProp Launcher install files to the application

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#209]
Add the BlocklyProp Launcher version 0.11.0 to the collection of installers available from within Solo. This will require updates to the UI to provide the additional selections. 

@zfi  - The Launcher installation files need to be staged in S3.

**Comment by zfi** [comment]
The new BlocklyProp Launcher files for Windows and MacOS have been staged to S3://downloads.parallax.com/blockly/clients/launcher/

Setup-BPLauncher-v0.11.0-MacOS.zip
Setup-BPLauncher-v0.11.0-Win.exe
Setup-BPLauncher-v0.11.0-Win.exe.zip

**Comment by MatzElectronics** [comment]
Should I remove the 32-bit Windows links?
Also, should I be adding some kind of UI/Links to the index.html page?

**Comment by zfi** [comment]
We're just adding the two launcher installers to the existing library of clients. No changes to the home page at this time.

**Comment by MatzElectronics** [comment]
Windows 32-bit?

**Comment by MatzElectronics** [comment]
Okay - I've got to do a couple of screenshot changes with this though - the screenshots are for the BPC, not the BPL.

**Comment by zfi** [comment]
@MatzElectronics is there an update on this issue?

**Comment by pjewald** [comment]
Launcher files are now available within the UI.
Closing the issue.
