### ISSUE TITLE
New block set for the LIS3DH 3-axis accelerometer

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#217]
Create new blocks for the LIS3DH 3-axis Accelerometer. Specifications are located [here](https://github.com/parallaxinc/Simple-Libraries/blob/3f120b0eea542934b9352a6ec9fded176ad16ba0/Learn/Simple%20Libraries/Sensor/liblis3dh/BLOCKS.txt). The Demo branch of the Simple Libraries repo contains the updates required to support these blocks.

**Comment by pjewald** [comment]
This will be included in the next release, which should happen later today.

**Comment by zfi** [comment]
These blocks have been released to production Solo.
Closing this issue.
