### ISSUE TITLE
Placing Serial initialize placing of additional blocks

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#224]
When placing the Communicate -> Protocols -> Serial initialize block, it snaps to the top-left of the visible canvas.  After that, it is not possible to any additional blocks.

**Comment by MatzElectronics** [comment]
This has been addressed (https://github.com/parallaxinc/solo/commit/a4cc0b35ad9ba685e4838064f219af56a72dc604#diff-58377024ea3cdba73390e5bec8a61ff8) - but the fix hasn't been released yet.

**Comment by MatzElectronics** [comment]
Never mind - still broken.  @pjewald can you assign this one to me?

**Comment by pjewald** [comment]
Track this issue's progress in issue #195.
Closing.
