### ISSUE TITLE
Array blocks and Robot blocks are breaking when used together

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#227]
One of my students put a bunch of blocks in his workspace and clobbered it somehow.
Still trying to diagnose this one (determine the cause and minimum code to replicate the bug).
Clobbers the workspace when it happens, and appears to be an interaction with the Array blocks.

**Comment by zfi** [comment]
@MatzElectronics is there any update to this report?

**Comment by MatzElectronics** [comment]
I'm struggling to replicate this - but I still have the original project that's causing the bug.  It's similar to many of the lockup bugs we've seen before, but I just need more time to pin it down.

**Comment by MatzElectronics** [comment]
I'm going to close this.  I'll reopen if I see it again when my kiddos start in on this.
