### ISSUE TITLE
Serial LCD toolbox flyout is empty

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#231]
In v.1.3.512, the Communicate/Serial LCD family of blocks are not being displayed when the Serial LCD element is clicked. The browser console is reporting a TypeError (see stack dump below). This error appears to have been introduced in PR #177. 

<img width="216" alt="Screen Shot 2020-01-10 at 8 51 58 AM" src="https://user-images.githubusercontent.com/8442260/72172972-53587c00-338b-11ea-937e-d2b9604b1562.png">

<img width="565" alt="Screen Shot 2020-01-10 at 8 51 29 AM" src="https://user-images.githubusercontent.com/8442260/72172921-420f6f80-338b-11ea-9c81-d07fde18a188.png">

**Comment by pjewald** [comment]
Verified that the PR corrected this issue.
Closing the issue.
