### ISSUE TITLE
LIS3DH Temperature block issue

### ISSUE THREAD

**Issue by ataylor-parallax** [parallaxinc/solo#242]
Projects including the LIS3DH Temperature block will not compile. Here is the compiler message:

Included libraries: lis3dh, simpletools
single.c: In function 'main':
single.c:19:34: error: expected ')' before ';' token
undefined

![image](https://user-images.githubusercontent.com/53913268/72383732-eae20580-36d0-11ea-9fa5-f7852d6395b0.png)

![image](https://user-images.githubusercontent.com/53913268/72383757-f7665e00-36d0-11ea-9312-82c3a813ce22.png)

**Comment by zfi** [comment]
@ataylor-parallax - please test against the v1.4.0 Solo. It should work as expected now.

**Comment by ataylor-parallax** [comment]
I have tested this and verified that it is fixed.
