### ISSUE TITLE
New block positioned under menu

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#25]
Adding a block to a new or existing project results in the new block partially hidden under the left menu. Adding a subsequent block causes the first block to be rendered in the visible area of the pallet and the new block is partially hidden under the left menu. 

![2019-07-16_11-26-44](https://user-images.githubusercontent.com/8442260/61319732-aa0a4200-a7bc-11e9-9872-112d37fdcaa3.png)

**Comment by MatzElectronics** [comment]
Lets check this everywhere:
https://github.com/google/blockly/issues/2482

**Comment by zfi** [comment]
Looks like we might need need to merge in the July, 2019 release of core Blockly to correct this issue. Unfortunately, this update also introduces a ton of changes to core.

**Comment by MatzElectronics** [comment]
Our current core isn't very old, so hopefully none of the new changes would
be breaking...

**Comment by zfi** [comment]
I am finding evidence that this problem may be caused by the metadata located in the .svg file. If I load a project that exhibits the error (blocks partially hidden under the left menu); save the project as a new file; then load that file, the blocks align to the upper-left corner of the editor canvas. 

The attached samples will hopefully illustrate the behavior. blink_27 exhibits the unwanted positioning when loaded. The A-blink_27 is the saved copy of the blink_27 project.

[blink_27.svg.zip](https://github.com/parallaxinc/solo/files/3536407/blink_27.svg.zip)
[A-blink_27.svg.zip](https://github.com/parallaxinc/solo/files/3536409/A-blink_27.svg.zip)

**Comment by MatzElectronics** [comment]
Here's a method for centering the project - we call call it on a short
timeout right after the project is loaded:
Blockly.getMainWorkspace().scrollCenter();

**Comment by zfi** [comment]
This [bug](https://github.com/google/blockly/issues/3032) was just filed in the Blockly project. It is very similar to this issue.

**Comment by zfi** [comment]
I just discovered that if the following steps are followed, the project appears in a reasonable place on the editor canvas.
* Load project from disk and store it into projectData.
* Save projectData to the browser localStorage
* Load the contents from the browser's local storage into projectData
* Call setupWorkspace()

I am thinking that this process is really just stripping off the graphics components of the svg file.

**Comment by MatzElectronics** [comment]
Can we revisit this?  
Right now, when I open a file, the blocks are forced into the top-left corner, and it's a bit obnoxious.  scrollCenter is a nice, clean way to position the blocks where they are easily accessed by the user, and the one proposed/attempted implementation was closed and not merged.

**Comment by zfi** [comment]
The project blocks have aligned with the upper left corner of the editor canvas for at least the past three years. Something broke when the blockly core was updated and that is what I thought we were trying to address in this issue. 

If we're not going to actually find and fix whatever broke, then we will center the blocks. We surely never want the block positioning to be obnoxious.

**Comment by zfi** [comment]
This issue is resolved.
Closing the issue.
