### ISSUE TITLE
Block Help links yield 500 Internal Server Errors

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#26]
Right-click any block and choose "Help" from the menu.  

Instead of going to the learn.parallax.com/ab-blocks/....  page appropriate for said block, a "Help and Reference" window with a 500 Internal Server Error nginx/1.15.12 opens.

**Comment by zfi** [comment]
This appears to correlate to a circular firing squad event logged on the server.

```
2019/07/16 21:31:10 [error] 6#6: *5 rewrite or internal redirection cycle while internally redirecting to "/rest/project/code/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html", client: 10.100.1.128, server: localhost, request: "POST /rest/project/code HTTP/1.1", host: "blockly-ecs-lb-707748549.us-west-2.elb.amazonaws.com", referrer: "http://blockly-ecs-lb-707748549.us-west-2.elb.amazonaws.com/blocklyc.html"
```

**Comment by zfi** [comment]
Menu > Help & Reference goes to here:

http://blockly-ecs-lb-707748549.us-west-2.elb.amazonaws.com/public/help 

....with a 500 error message.  Expected it to go here:

https://learn.parallax.com/support/reference/propeller-blocklyprop-block-reference

**Comment by pjewald** [comment]
Offline help appears to not exist. There is a reference to a /cdn/help folder that is missing.

**Comment by Steph-Parallax** [comment]
Offline help is not needed nor desirable for Solo; the links should go to the online Help.  How Help is handled needs to diverge between Solo and Local.  Ideas?

**Comment by PropGit** [comment]
If offline is to be true to its name, maybe a pdf of the current online help at the time can be created and included with and linked to by the offline system.

If that's harder said than done (as it really begs to be automated in some way), then the best solution is just to provide the same online link as with the others, but with the menu item renamed to "Online Help."  At least that way, it advertises that the help is not offline.

**Comment by Steph-Parallax** [comment]
[Propeller BlocklyProp Block Reference.pdf](https://github.com/parallaxinc/solo/files/3404011/Propeller.BlocklyProp.Block.Reference.pdf)
This took a few clicks, no post processing; it is 140 pages.  It would benefit from post processing, of the  straightforward and delegatable type. It might be possible to manage with Learn site printer-friendly-version stylesheet changes but that could be a more difficult project.

**Comment by zfi** [comment]
The offline version will store the help PDF and the client installers within the docker image. We will need to update the build process to incorporate these changes, but that should be a fairly trivial task.

**Comment by pjewald** [comment]
The original issue was the server 500 error. That issue appears to be resolved with the PRs noted in previous comments.

A new issue #43 has been created to address offline help.

Closing this issue.
