### ISSUE TITLE
Update LIS3DH block set

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#265]
* Add a tilt block as described [here](https://github.com/parallaxinc/Simple-Libraries/blob/BlocklyProp/Learn/Simple%20Libraries/Sensor/liblis3dh/BLOCKS.txt).
* Update the LIS3DH init block to support the new tilt block.

**Comment by Steph-Parallax** [comment]
Testing LIS3DH blocks in Solocup. Typo found in LISD3H read voltage mV block emit code. 
This causes compiler fail:
`void CheckAD() {
  lis3dh_adc_mv(lis3dh_sensor, &AD1_V, &item, &item);
  print("%s%d\r", "AD1 voltage/100 = ", AD1_V);
}`

Capitalizing the V in lis3dh_adc_mV(); lets the code compile (tested in SimpleIDE)
`void CheckAD() {
  lis3dh_adc_mV(lis3dh_sensor, &AD1_V, &item, &item);
  print("%s%d\r", "AD1 voltage/100 = ", AD1_V);
}`

(I did not test the other ADC channels as those are pad-only access.)

Blocks file I used is attached.
[29020-LIS3DH-Test-ADCsvg.zip](https://github.com/parallaxinc/solo/files/4233242/29020-LIS3DH-Test-ADCsvg.zip)

**Comment by zfi** [comment]
@MatzElectronics, I rolled back PR#289 because it breaks the attached test project. It works great if the adc_mV is reverted back to adc_mv in both places where the change occurred. 

[29020-LIS3DH-Test-ADCsvg.zip](https://github.com/parallaxinc/solo/files/4234437/29020-LIS3DH-Test-ADCsvg.zip)

**Comment by MatzElectronics** [comment]
It makes sense that a project created before that fix would break.  You could search for "adc_mv" and replace it with "adc_mV" in the SVG, and since we aren't checksumming, that would make the test program work.

**Comment by zfi** [comment]
Ok, no one had an understanding that the change to correct the compilation error was also data persisted in the profile file. The 'adc_mV' in back in place; the project file hacked and included below. The develop branch in back in business.

[29020-LIS3DH-Test-NO-ADC-rev1.svg.zip](https://github.com/parallaxinc/solo/files/4234513/29020-LIS3DH-Test-NO-ADC-rev1.svg.zip)

**Comment by MatzElectronics** [comment]
Yeah - it makes for more efficient code to share the code gen with field values, but it does have it's drawbacks - this example being the big one.
