### ISSUE TITLE
Save project reminder problems

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#27]
If I choose Save, I get a message that my project could not be saved, and I must log in again. Logging in is nonsequitir (and the message has a typo.)

![image](https://user-images.githubusercontent.com/22827298/61338921-65989980-a7f0-11e9-8d1c-3d2642a41d9e.png)

If I choose Save As and Confirm, no .svg file is downloaded, which is the behavior I see when I click Save from the top bar.    So, I don't think anything is happening at all.

In any case, having both Save and Save As options seems redundant since Save currently behaves as a Save As anyway.

**Comment by pjewald** [comment]
@MatzElectronics, which PR addresses this issue?

**Comment by MatzElectronics** [comment]
It was addressed in [CDN-170](https://github.com/parallaxinc/BlocklyProp-cdn/commit/39a8aafc67d014b7d66e472a10d013608d931af7)

**Comment by pjewald** [comment]
Thanks. For future success, please enter the issue references individually. GitHub appears not to support compound issue references or the way they were written is not supported. The solo-27,28,30 did not create links from the PR back into the related issues.

```
Ensures saving is routed through download mechanisms when offline/solo modes are enabled.
Should address #165, solo-27,28,30
```

whereas referencing them individually did work as expected.
```
Addresses parallaxinc/solo#27
Addresses parallaxinc/solo#28
Addresses parallaxinc/solo#30
```

**Comment by PropGit** [comment]
Simply entering the numbers with a # in front of them works, like #27, #28, #30.

**Comment by zfi** [comment]
@PropGit , that works if you are referencing issues in the same repo. In this case, the PR was in the CDN repo, and the referenced issues were in the Solo repo, hence the need to provide the full reference.

**Comment by PropGit** [comment]
I see; I misunderstood the context.

**Comment by zfi** [comment]
Further testing indicates that this issue has been resolved. 
Closing the issue.
