### ISSUE TITLE
Restore "debug" URL flag

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#271]
This could be done with the experimental flag as another value (?experimental=debug).

All `console.log`'s should be being this flag, and this flag should open up the XML editor pane.

**Comment by zfi** [comment]
Let's consider using a lightweight logging framework for debugging messages sent to the console. I am partial to [Log4js](https://stritti.github.io/log4js/). With that, we can adjust the verbosity (logging level) from a query string.

I would also like to see the a separate query string element to enable the XML editor pane.
