### ISSUE TITLE
Hide terminal beep sound file.

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#272]
It's showing, and it shouldn't be.  The JS that creates it inside of propterm.js needs to have `display: 'none'` added to it's CSS.

![image](https://user-images.githubusercontent.com/19737272/74209033-e3177180-4c3a-11ea-9cf2-ea0cab585df3.png)

**Comment by zfi** [comment]
@MatzElectronics, can you submit a PR with the changes needed to correct this? It seems like low-hanging fruit.

**Comment by MatzElectronics** [comment]
It is on my todo late this evening.
