### ISSUE TITLE
Project importing broken?

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#273]
I can't seem to import any projects (as opposed to opening them).

**Comment by MatzElectronics** [comment]
Related to #261 - but importing doesn't seem to be working at all.

**Comment by pjewald** [comment]
The work done on issue 261 is on a separate branch from develop, so not likely relevant here.  Are there any specific details available, such as what version of the build is failing; any console error messages;  verify that this is happening on the develop branch; etc.

**Comment by zfi** [comment]
Further investigation show that the checksum on the imported file is no longer matching the checksum stored in the project file.

**Comment by zfi** [comment]
It appears that code in the editor.js:uploadHandler() is correctly identifying a checksum mismatch, but then there are two things happening and they are both broken.

1) If the project checksum and the computed checksum do not match, the project should not be loaded, but there is nothing in code that interrupts the loading process until after the project has been loaded into the browser localStorage.

2) There is a test for valid XML at the bottom of uploadHandler(). This code is correctly detecting that uploadXML is false, but the HTML element is not being selected as it should but only when we are opening a project. It appears to work as expected once a project is loaded, such as when a project is imported into an existing project and that imported project fails the checksum computation.

```
       if (xmlValid === true) {
            $('#selectfile-verify-valid').css('display', 'block');
            document.getElementById("selectfile-replace").disabled = false;
            document.getElementById("selectfile-append").disabled = false;
            uploadedXML = xmlString;
        } else {
            $('#selectfile-verify-notvalid').css('display', 'block');  <<=====
            document.getElementById("selectfile-replace").disabled = true;
            document.getElementById("selectfile-append").disabled = true;
            uploadedXML = '';
        }
```

@MatzElectronics, Any thoughts on why the checksum computation is failing?

**Comment by MatzElectronics** [comment]
Probably because the XML header itself is different with the newer core.
That being said - we should get rid of the checksum.  It was a measure used
to protect the server from malicious code getting into the database, but
since this is all client side, that is no longer necessary.

**Comment by zfi** [comment]
Alright, we can deprecate the checksum feature. However, the checksum is the only test we apply to the project during open or import. That would likely mean that we need to be more diligent when applying the project code to Blockly Core to trap any complaints about malformed blocks.
