### ISSUE TITLE
Case mutator does not add more cases.

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#277]
When I try to use the case mutator to add more cases, I can stack cases in the popup extension, but it does not add cases to the block itself.

**Comment by MatzElectronics** [comment]
Is this a bug?  I'm not able to replicate the problem - is there are chance you could do a video/google hangout?

**Comment by phil-pilgrim** [comment]
Here's an image:
![case_issue](https://user-images.githubusercontent.com/61169172/74693280-f75df000-519f-11ea-8570-bc48615b1305.png)

**Comment by MatzElectronics** [comment]
Okay, can you save and send me the project SVG?  I'd like to try to
diagnose the bug.

**Comment by phil-pilgrim** [comment]
After saving my project SVG, then reloading it, adding cases has started working. So I doubt you'll be able to replicate the intermittent behavior I observed.

**Comment by MatzElectronics** [comment]
Okay - thanks for reporting regardless - it's something that I can keep an eye out for.  One thing you can do too is to capture the console log.  Most errors will be reported there.  You can access it under the top-right menu > more tools > developer tools > console.  A screenshot or copy paste of that can be really helpful.

**Comment by pjewald** [comment]
Closing this issue. Feel free to reopen it if the error returns.
