### ISSUE TITLE
Pin blocks need expression value input.

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#278]
In blocks that reference the I/O pins, the pin numbers have to be selected from a drop-down list. This is much too restrictive. Those arguments should be regular constant/value/expression inputs.

**Comment by MatzElectronics** [comment]
Most blocks that have this input have an option at the bottom of the menu
that says "other".  When you select other, the block mutates and changes to
an expression input, just as you are looking for.

Is there are block that does not have this that you need it on?

**Comment by phil-pilgrim** [comment]
Sorry. I'm totally new to this and did not scroll down far enough to see the "other." Thanks! Issue closed.

**Comment by MatzElectronics** [comment]
No problem - sometimes it's difficult to communicate all of the niche little features in the system.  Always ask, though!  We love to see how people use the system and some of the best ideas have come from "I need it to do X and Y...".
