### ISSUE TITLE
Refactor (make object/class) client connection code

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#279]
Adding as a task issue for resubmitting refactoring work done against solo-#200.

**Comment by pjewald** [comment]
@MatzElectronics, are there more PRs for this or are we done with the refactoring? Looking for an endgame on this issue.

**Comment by MatzElectronics** [comment]
Several more.  I had cleaned it up A LOT as part of #200 - so I don't want
to loose that work - it will *vastly* simplify the connection/client code,
especially once we remove support for the BPC.

**Comment by zfi** [comment]
@MatzElectronics, let's iterate through these over the next couple of weeks and close it out.

**Comment by MatzElectronics** [comment]
Finished - this is ready to be verified and closed.
