### ISSUE TITLE
Not logged in error when saving a project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#28]
This dialog should not appear in Solo. The concept of user accounts does not exist in this context. If there is an underlying cause for the error message, such as a file system error, we should report that instead. 

![image](https://user-images.githubusercontent.com/8442260/61346553-14979e00-a80e-11e9-859e-2e074c2c83af.png)

**Comment by PropGit** [comment]
Similar to Issue #27

**Comment by pjewald** [comment]
Tracking this issue with #27 as they are both referencing the same error message but with slightly different triggers.

Closing.
