### ISSUE TITLE
code view has volume control icon over code at bottom

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/solo#284]
Assuming this is due to Chrome handling of .svg files, that it "helpfully" pops up a volume control.

You see it when clicking "New" project, and also in code view. With long code, the icon covers the code bottom-left.

Couple images attached show the volume control, bottom left.
Doesn't seem super high priority, but would be nice to clean away the volume control.

![2020-02-19 11_18_54-Simple-Libraries-BlocklyProp](https://user-images.githubusercontent.com/11635798/74825413-2e501500-530a-11ea-8d66-b56662c6535b.png)
![2020-02-19 11_19_43-](https://user-images.githubusercontent.com/11635798/74825420-314b0580-530a-11ea-84e4-beaf8f44304f.png)

**Comment by MatzElectronics** [comment]
This is the same as #272.  Thanks!  I'll close this and work through that issue.
