### ISSUE TITLE
Suggestion: a "corral" for user-defined blocks

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#288]
In working with user-defined blocks, it would be handy to have a "corral" for ones that are not used in one's program. They would not be compiled but would still be part of the user's SVG file. The corral would work similarly to the side menu in Blockly (and could be merged into it), in that user blocks dragged out of the corral would automatically be duplicated, rather than disappearing from the corral..

As it now stands, a user who loads or imports a program that includes user-defined blocks will permanently lose any blocks that they might happen to delete. A corral would prevent that from happening. Basically, a corral would amount to an enhanced programming toolset that can be imported into the user's workspace.

**Comment by zfi** [comment]
The side menu (the toolbox) is populated with statically defined blocks. The blocks that are included in the toolbox can change based upon the selected board type. To get to the corral concept, the toolbox would need to be able to dynamically load a set of custom block definitions that are somehow pre-populated with the used-defined blocks configuration options. I think this infers that we would need code that loads the user-defined blocks; generate the code to define the blocks (to make them selectable from the toolbox); and then inject that code into the toolbox.

Some of this can be approximated by saving the group of custom blocks into a separate project file; then importing the custom blocks project into the main project. Individual blocks can be disabled or removed from the project as needed.

As for losing blocks that are deleted, I'm not following the consequence of deleting a block. The blocks are still in the project that was imported so the deletion does not impact that project. I would like to understand this concern more clearly.

**Comment by MatzElectronics** [comment]
This is an interesting idea...
It would probably work in a manner similar to the variable or function menus in the toolbox.  When you create a user defined block, it would simply appear in its own category, and those blocks could then be tracked in the project's XML separately so they didn't get deleted unless the user explicitly deleted them - just like variables.

That being said, this is a pretty involved request, and one that I'm not sure the team has the bandwidth for currently.  Not my call, but I can provide an estimate of what's involved and it's not trivial.

**Comment by phil-pilgrim** [comment]
_"Some of this can be approximated by saving the group of custom blocks into a separate project file; then importing the custom blocks project into the main project. Individual blocks can be disabled or removed from the project as needed."_

As it stands, I can import a template project with the initialization block enabled and the action blocks disabled, over on the side next to the menu, ready to deploy. Two things would help here:

1. The disabled blocks are barely readable, i.e. the background is light and the text is white. It would be better to have more color contrast or some other way to designate that they are disabled.

2. When you duplicate a disabled block, the duplicate block should automatically be enabled.

This would be almost as good as having a corral or the blocks inserted into the menu.

_"It would probably work in a manner similar to the variable or function menus in the toolbox. When you create a user defined block, it would simply appear in its own category, and those blocks could then be tracked in the project's XML separately so they didn't get deleted unless the user explicitly deleted them - just like variables."_

Yes!

**Comment by phil-pilgrim** [comment]
Jim or Matt,

Is the decimal value in the SVG's <ckm> field a CRC-32? If not, what is it? Which part of the file is it computed on? And is there an extra "key" that is is thrown in with the SVG text (ahead of? after?) before computation?

Thanks,
-Phil

**Comment by MatzElectronics** [comment]
Not exactly - we will be removing the check itself in the next update and
replacing the field in the file with zeros.

If you're curious, here's the code that generates it:
/**
 *
 * @param {string} str
 * @returns {number}
 */
function hashCode(str) {
    let hash = 0, i = 0, len = str.length;
    while (i < len) {
        hash = ((hash << 5) - hash + str.charCodeAt(i++)) << 0;
    }
    return (hash + 2147483647) + 1;
}

And it was applied only to the string representation of the XML of the
blockly project itself, not the entire SVG - starting at <block> or <block>,
whichever came first, and ending at (not inclusive) </svg>.

**Comment by MatzElectronics** [comment]
Not exactly - we will be removing the check itself in the next update and
replacing the field in the file with zeros.

If you're curious, here's the code that generates it:
```
/**
 *
 * @param {string} str
 * @returns {number}
 */
function hashCode(str) {
    let hash = 0, i = 0, len = str.length;
    while (i < len) {
        hash = ((hash << 5) - hash + str.charCodeAt(i++)) << 0;
    }
    return (hash + 2147483647) + 1;
}
```
And it was applied only to the string representation of the XML of the
blockly project itself, not the entire SVG - starting at `<block>` or `<variable>`,
whichever came first, and ending at (not inclusive) `</svg>`.

**Comment by phil-pilgrim** [comment]
So to be clear, I chop everything off the beginning of the SVG file, up to but not including the first **<block** or **<variable** and off the end that includes, say, **<ckm>001754473171</ckm></svg>**.
If I apply the algo to what remains, I should end up with the number that was originally between **<ckm>** and **</ckm>**, right?

**Comment by zfi** [comment]
This doesn't directly answer your question, but the checksum is getting retired in the next release. We are maintaining the tag in the file for the next couple of releases. This means there is no need to compute the checksum.

Your understanding for the computation is correct. The problem you may encounter is that the checksum you compute my not match the value in older projects. It's a problem we discovered after we released a build with an updated Blockly core and a contributing factor in the decision to deprecate it.

**Comment by phil-pilgrim** [comment]
Thanks, Jim. Although I realize that the checksum is going away, I have an immediate need to load modified SVGs as an experiment, and I can't do it unless the checksum is correct.

The reason I asked my question is that I'm not getting the same result and thought I might be computing on the wrong text. Here's my Perl program that performs your algo (sans the SVG file after __DATA__):

`my $svg;

while (<DATA>) {
	$svg .= $_
}

$svg =~ s/(<ckm>\d+<\/ckm><\/svg>)//;

print "$1\n\n";
$svg =~ m/((<block|<variable).*)/;
$svg = $1;
$svg =~ s/[\n\r]//g;
#$svg =~ s/&quot;/\"/g;\
print "$svg\n\n";
my $hash = 0;

foreach my $i (0 .. length($svg) - 1) {
	$hash = (($hash << 5) - $hash + ord(substr($svg, $i, 1)))
}
$hash = ($hash + 0x7fffffff) + 1;
print $hash;


__DATA__
`
The SVG's checksum is **001754473171**. I'm getting **6691926897**.

**Comment by MatzElectronics** [comment]
It's probably easier to override it in the console.

Open the console using the 3 dot menu at the top-right > more tools > Developer tools > console

Paste this in at the prompt:
```
function uploadMergeCode(e){if($("#upload-dialog").modal("hide"),e||"true"!==window.getURLParameter("openFile")||(window.localStorage.setItem(LOCAL_PROJECT_STORE_NAME,window.localStorage.getItem(TEMP_PROJECT_STORE_NAME)),window.localStorage.removeItem(TEMP_PROJECT_STORE_NAME),window.location="blocklyc.html"+window.getAllURLParameters()),""!==uploadedXML){var a="";e&&(a=(a=(a=getXml()).substring(42,a.length)).substring(0,a.length-6));var l=uploadedXML;if((l=(l=-1===l.indexOf("<variables>")?l.substring(uploadedXML.indexOf("<block"),l.length):l.substring(uploadedXML.indexOf("<variables>"),l.length)).substring(0,l.length-6)).indexOf("<variables>")>-1&&a.indexOf("<variables>")>-1){var o=/type="(\w*)" id="(.{20})">(\w+)</g,r=[],i=[],t=l.split("</variables>");l=t[1];var n=t[0].split("<variables>")[1].replace(o,function(e,a,l,o){return r.push([o,l,a]),e});t=a.split("</variables>"),a=t[1],n=t[0].replace(o,function(e,a,l,o){return i.push([o,l,a]),e}),n=[i.length,r.length];for(var d=0;d<n[0];d++)for(var s=0;s<n[1];s++)if(r[s][0]===i[d][0]){var E=l.split(r[s][1]);l=E.join(i[d][1]),r[s][1]=null}for(s=0;s<n[1];s++)r[s][1]&&i.push(r[s]);n="<variables>",i.forEach(function(e,a){n+='<variable id="'+e[1]+'" type="'+e[2]+'">'+e[0]+"</variable>"}),n+="</variables>",projectData.code=EMPTY_PROJECT_CODE_HEADER+n+a+l+"</xml>"}else l.indexOf("<variables>")>-1&&-1===a.indexOf("<variables>")?projectData.code=EMPTY_PROJECT_CODE_HEADER+l+a+"</xml>":projectData.code=EMPTY_PROJECT_CODE_HEADER+a+l+"</xml>";ClearBlocklyWorkspace(),loadToolbox(projectData.code),clearUploadInfo(!1)}}
```

I haven't tested this, but I think it should work.

**Comment by phil-pilgrim** [comment]
This is all I get from the 3-dot menu:
![three_dot](https://user-images.githubusercontent.com/61169172/75005933-ed98ee80-5424-11ea-92a6-63c067b160bb.png)

**Comment by MatzElectronics** [comment]
Yup - I'm referring to the menu for Chrome/Firefox itself.

**Comment by phil-pilgrim** [comment]
Okay, I loaded the SVG file in Chrome and did what you suggested, but I'm not sure what's supposed to happen from that point. BTW, my Blockly Solo isn't running in Chrome but in some other environment dictated by BPLauncher.exe.

**Comment by MatzElectronics** [comment]
You were able to get to the browser console okay then?  The code I sent is a rewrite of the function that does not check for a checksum, so it will "pass" the file regardless of what the checksum is - If it works, after you've pasted it in, you should be able to do an import of another block file (not an "open", but an "import" from the blockly 3 dot menu) without it failing the file.

**Comment by phil-pilgrim** [comment]
> You were able to get to the browser console okay then?
Yes, but not from Blockly. I opened the SVG file in Chrome.

So do I paste your code in ahead of the SVG text, then save the SVG file to be loaded into Blockly?

**Comment by MatzElectronics** [comment]
Yes:
 - open a blank project
 - paste in the new function into the browser console
 - import your blocks/modified SVG
 - resave

**Comment by phil-pilgrim** [comment]
The problem I'm seeing is that Blockly is not running in a browser, but in its own environment. So there's no console available to enter stuff into. I can open an SVG file in Chrome, but that does not bring in all the JS stuff that Blockly needs; it just displays the graphic. So entering code into Chrome's developer console doesn't do anything, because Blockly's programming context is absent.

**Comment by MatzElectronics** [comment]
I'm so sorry for the back-and-forth on this.

With the launcher running, open a new tab in Chrome and go to https://solo.parallax.com instead of clicking the button on the lanucher.  Then try what I suggested above.

**Comment by zfi** [comment]
What @phil-pilgrim is seeing is the Chromium web browser embedded in the Launcher package. It's the same engine as the Chrome browser but it's missing all of the niceties of Chrome.

**Comment by phil-pilgrim** [comment]
Got it. Tried the script. Console answered, "undefined." So still can't load an SVG with a bad checksum. I get, "The selected file is not valid."

**Comment by MatzElectronics** [comment]
Bummer...let me dig in a bit more this afternoon - I'll probably give you a
different code snippet to try.  The "undefined" is the expected response
because the function is not returning anything.

**Comment by MatzElectronics** [comment]
Okay - let's try a different way.  I have something you might find really helpful.
Paste this into your browser console:
```
function renderContent(o){const e=o.replace("tab_",""),l="propcfile"===projectData.board;let n=!0;switch(n||(n=!1),l&&$(".propc-only").removeClass("hidden"),e){case"blocks":$(".blocklyToolboxDiv").css("display","block"),$("#content_xml").css("display","none"),$("#content_propc").css("display","none"),$("#content_blocks").css("display","block"),$("#btn-view-xml").css("display","none"),$("#btn-view-propc").css("display","inline-block"),$("#btn-view-blocks").css("display","none"),n&&codeXml.getValue().length>40&&Blockly.Xml.clearWorkspaceAndLoadFromXml(Blockly.Xml.textToDom(codeXml.getValue()),Blockly.mainWorkspace),Blockly.svgResize(Blockly.mainWorkspace),Blockly.mainWorkspace.render();break;case"propc":if($(".blocklyToolboxDiv").css("display","none"),$("#content_xml").css("display","none"),$("#content_propc").css("display","block"),$("#content_blocks").css("display","none"),$("#btn-view-xml").css("display",n?"inline-block":"none"),$("#btn-view-blocks").css("display",l||n?"none":"inline-block"),$("#btn-view-propc").css("display","none"),l){if(codePropC&&""!==codePropC.getValue()||(codePropC.setValue(atob((projectData.code.match(/<field name="CODE">(.*)<\/field>/)||["",""])[1]||"")),codePropC.gotoLine(0)),""===codePropC.getValue()){let o="// ------ Libraries and Definitions ------\n";o+='#include "simpletools.h"\n\n\n',o+="// ------ Global Variables and Objects ------\n\n\n",o+="// ------ Main Program ------\n",o+="int main() {\n\n\nwhile (1) {\n\n\n}}";let e=prettyCode(o);codePropC.setValue(e),codePropC.gotoLine(0)}}else{let o=prettyCode(Blockly.propc.workspaceToCode(Blockly.mainWorkspace));codePropC.setValue(o),codePropC.gotoLine(0)}break;case"xml":$(".blocklyToolboxDiv").css("display","none"),$("#content_xml").css("display","block"),$("#content_propc").css("display","none"),$("#content_blocks").css("display","none"),$("#btn-view-xml").css("display","none"),$("#btn-view-propc").css("display","none"),$("#btn-view-blocks").css("display","inline-block"),codeXml.setValue(Blockly.Xml.domToPrettyText(Blockly.Xml.workspaceToDom(Blockly.mainWorkspace))),codeXml.getSession().setUseWrapMode(!0),codeXml.gotoLine(0)}}
```

Now, when you click the code button to view the PropC generated, you'll get a new button - instead of taking you back to the blocks, you get a tab to edit the XML directly.  In the XML editor tab, the blocks button is available again (you cycle from "blocks" > "code" > "xml" > "blocks"...)

**Comment by phil-pilgrim** [comment]
I get the **XML** button, but when I click it, I get the following error message in the console, instead of an XML edit tab or window:

> VM811:1 Uncaught TypeError: Cannot read property 'setValue' of null
    at renderContent (<anonymous>:1:1993)
    at HTMLAnchorElement.<anonymous> (editor.js:660)
    at HTMLAnchorElement.dispatch (jquery-1.11.3.min.js:26)
    at HTMLAnchorElement.r.handle (jquery-1.11.3.min.js:26)

**Comment by MatzElectronics** [comment]
okay - we are close!!!!  I just found this one too.  Add `?debug=true` to the end of the URL and reload it with that there.  Then, re-paste in the code, then try the tab.  I had that on my end and forgot to tell you to have it there too.

**Comment by phil-pilgrim** [comment]
Okay, did that, and re-pasted your script. But now I'm not getting the XML button. It just toggles between **Blocks** and **Code**. However, running the script does cause a screen refresh, as it did before.

**Comment by MatzElectronics** [comment]
Hmmm...it's not sticking.  Is there a way you can do a google hangout
around 3:15 PST?

**Comment by phil-pilgrim** [comment]
Maybe. I'll have to do it on my Mac, and I have to install some stuff first. I'll let you know ...

**Comment by phil-pilgrim** [comment]
Rats! Can't run BPLauncher on my Macbook (OS X is too old). And I don't have a webcam or sound on my PC.

**Comment by MatzElectronics** [comment]
Can you email me at matt dot m dot matz at gmail dot com with your email?
I can call you and we can figure something out.

**Comment by phil-pilgrim** [comment]
Emailed. Thanks!
