### ISSUE TITLE
BP Solo browser tab says BlocklyProp Local

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#29]
The browser tab should be set to the correct brand (solo / local). 

![image](https://user-images.githubusercontent.com/8442260/61346748-f7af9a80-a80e-11e9-91c0-0c769101445a.png)

**Comment by pjewald** [comment]
@MatzElectronics, this is an element of the inc_templates that was missed in the initial pass. Feel free to use this issue to refactor those HTML templates into a JavaScript implementation that uses an environment variable to set the application brand name.

**Comment by pjewald** [comment]
Hard-coded 'Solo' as the default branding when issues like this appear.

**Comment by MatzElectronics** [comment]
I don't want to mess up the docker config, so can I ask you to get the ENV stuff setup on the docker side, and I'll implement it on the client-side once it's there?

https://medium.com/code-build/docker-environment-variables-and-nginx-93d7173f19ec

**Comment by zfi** [comment]
Let's take that discussion offline.

**Comment by zfi** [comment]
Recap: This issue has been resolved by hard-coding the correct branding. 
Closing this issue.
