### ISSUE TITLE
Saving an empty project creates invalid svg file

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#31]
SL reports:

If I save a project with no blocks in it, I cannot open it. I get the "this project is invalid" message.  I feel that it should throw a warning that a project must have at least one block before saving it, if it will not be valid to open again later.  

Same behavior as BP Production, by the way.

**Comment by zfi** [comment]
Steps to reproduce the error:

* Open a new project. Fill out the project details and get to the editor canvas.
* Save the project.
* Navigate to the home page and select the Open Project link.
* Select the project that was just saved in the previous steps.

The open dialog reports the following:
![2019-08-02_11-33-58](https://user-images.githubusercontent.com/8442260/62391523-e8706280-b519-11e9-99b9-00e94a7eb389.png)

The svg file:

[aaaaa.svg.zip](https://github.com/parallaxinc/solo/files/3462528/aaaaa.svg.zip)

**Comment by pjewald** [comment]
The correction to this issue was to disallow saving an empty project.
Issue is resolved. Closing.
