### ISSUE TITLE
Add checkbox option to user-defined blocks

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#319]
I'm designing servo drivers for a robot arm. As it currently stands, each servo has a block that sets its position and velocity, then waits for the motion to reach it's destination before continuing to the next block. I would like the wait to be an option that the user could set with a checkbox, like the newline option in the Terminal blocks. When the box is checked, a variable associated with the checkbox would be set to **true**, which a conditional in the main C code could check,

Can this be done? If not, I guess I can settle for a third parameter that can be set to **true** or **false**.

**Comment by MatzElectronics** [comment]
While it could technically be done, the complexity of adding additional
field types like dropdowns or checkboxes would be prohibitive.  I can look
at what's involved, but I don't think it will be easy.  The other
consideration is backward compatibility with the current block if the new
one is different.

**Comment by phil-pilgrim** [comment]
I'm not too worried about backward compatibility, since nothing I've written has been released yet. 'Still in the initial dev stage.

**Comment by MatzElectronics** [comment]
What I mean by backward compatibility is when we make changes to a block,
if we aren't careful, and user projects with the older version of the block
will break, and render their projects useless.

**Comment by phil-pilgrim** [comment]
Okay, I get it now: it's the new features added to raw blocks in the toolbox that can cause trouble. And it'd be crazy to proliferate new block types just to add new features to an existing block. A conundrum for sure.

I'm pretty happy to do it this way:

![arm_tools](https://user-images.githubusercontent.com/61169172/75634022-bf52a600-5bbe-11ea-9ed9-958803321b97.png)

'Really loving the custom toolbox category, BTW!

**Comment by MatzElectronics** [comment]
If you want to "lock" your custom blocks, edit the XML so the type of those blocks is `custom_code_multiple_locked`.  You can also add `colour="#HEXVAL"` to the category block to give it the same color pip that the other menu categories have.  Just replace HEXVAL with a html color value that you want to use.

I'm going to close this issue, thanks!
