### ISSUE TITLE
Modifying C code in a user-defined block

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#320]
I've noticed that when I modify the C code in a user-defined block, it only gets changed in the instance I modify -- not in other instances of the same block, Is this what's supposed to happen?

**Comment by MatzElectronics** [comment]
Yes.  But I can investigate what would be involved in changes propagating
across custom blocks that have the same name.

**Comment by phil-pilgrim** [comment]
That would be nice, although I don't think it needs to be a priority. Thanks.

**Comment by MatzElectronics** [comment]
Okay, whileni like the idea myself, too...it would take quite a bit of work to make it happen.  Closing this one for now. It can always be reopened.
