### ISSUE TITLE
Connection to BlocklyProp Client fails on CORS error

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#323]
Related to issue #200 

The browser is unable to maintain a connection to the Launcher (0.11.0) when the browser is using a TLS connection to Solo.  The console reports the following error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:6009/. (Reason: CORS request did not succeed).
```

The call that appears to create this situation is in blocklyc.js:617. It using the default protocol to establish a connection with the BlocklyProp Client/Launcher.
```
                if (clientService.version.isCoded) {
                    //Request load with options from BlocklyProp Client
                    $.post(clientService.url("load.action"), {  // <<========
                        option: load_option,
                        action: load_action,
                        binary: data.binary,
                        extension: data.extension,
                        "comport": getComPort()
                    }, function (loaddata) { 
                 [ ... ]
```

**Comment by MatzElectronics** [comment]
Using the launcher, correct?  This code shouldn't be called at all unless the BPC (not BPL) is being used.  I'll try to see why it's trying to call that code.

**Comment by zfi** [comment]
I am running a project that uses the terminal. The program downloads and runs for between 10 and 20 seconds. After that interval, the editor page indicates that the client is unavailable, followed by a message that reports that the browser is connected to the client. When the initial 'client is unavailable' message appears, the activity in the terminal halts.

**Comment by zfi** [comment]
I'm no longer convinced that the code I pointed to is the issue. What is broken is the protocol. HTTPS will never work when trying to establish a connection to the Launcher.

**Comment by MatzElectronics** [comment]
@PropGit any thoughts on this?
FWIW - I'm using a Mac with 10.13 High Sierra - and I cannot get the BP-Launcher to load code.  It always fails (Propeller not found) lately.  BPC works consistently.

**Comment by zfi** [comment]
Look at the first entry.

**Comment by pjewald** [comment]
The USB ports on the Mac become unavailable due to an error in the driver. A cold restart is required to unlock the ports.

The issue here appears to have surfaced after Solo #200 E/F (PR #317 PR #318)  was accepted into the project.

**Comment by MatzElectronics** [comment]
Okay - I can't replicate this because my container/localhost can't provide
a secure connection.

**Comment by zfi** [comment]
use https://solocup.parallax.com

**Comment by pjewald** [comment]
It looks like this may be triggered when the heartbeat fails. It finds that the connection is closed and then attempts to use HTTPS when re-establishing the connection. 

![Screen Shot 2020-03-02 at 1 33 08 PM](https://user-images.githubusercontent.com/11216070/75719879-694b3480-5c8a-11ea-9448-befdc7104044.png)

**Comment by MatzElectronics** [comment]
Okay - heartbeat is next up in my pursuit of finishing #200.

**Comment by pjewald** [comment]
Further testing with the new BlocklyProp Launcher 0.11.1 seems to mask whatever is going because the connection failures are virtually nonexistent.

**Comment by PropGit** [comment]
I haven't changed any code in v0.11.0 or v0.11.1 that relates to the connection with the browser and BP Launcher has been working in a secure fashion against Production for > 1 year.  Something else has changed causing this problem.

**Comment by PropGit** [comment]
> @zfi - BPL or BPC?
> @PropGit any thoughts on this?
> FWIW - I'm using a Mac with 10.13 High Sierra - and I cannot get the BP-Launcher to load code. It always fails (Propeller not found) lately. BPC works consistently.

I've tested on Mohave and Catalina, but not High Sierra specifically.  There is a problem I noticed where the download will fail for reasons I haven't determined, and attempting another download or two usually works.  It only happens rarely for me, so I solved other problems first and intent to solve this one pretty soon.  Can you try terminating any software that's running in the background to see if the download success frequency improves?

Also, make sure you're using FTDI driver v2.4.2 on your computer.  v2.3 causes port lockouts.  You can check which one you're running by using Finder to navigate to /Library/Extensions and click on the FTDIUSBSerialDriver.kext, then look for the version in the file preview pane.  v2.4.2 clearly says that in version... I think v2.3 doesn't say anything for version.

**Comment by zfi** [comment]
Considerable work has gone into the Launcher <-> Solo interface code. We have not had a single hit on this issue in several weeks.

Closing the issue but will reopen it if we see this again.
