### ISSUE TITLE
Terminal window

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#327]
Would it be possible to make the Terminal output window movable and scalable? Sometimes I need to see code in the background that it's covering up -- especially when the window is reporting one thing, and what I asked for in the code is something else. I can exit the Terminal window and move the code, but it would be easier just to move the window.

I guess the same could also apply to the Graph window, although I've never used it and don't know if the same issue exists.

Thanks!

**Comment by zfi** [comment]
I think that making the window moveable is a good first step. The other aspects are more complicated because the terminal is not a virtual window.

**Comment by MatzElectronics** [comment]
Can I tackle this one?  I found some extensions to jQuery that would work well for this.

**Comment by zfi** [comment]
I think we're still trying to figure out what it will take to get from where we are to where we need to be. We should resolve that before we spend any time on coding.
