### ISSUE TITLE
Saving file when in Firefox shows source as from:blob:

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#33]
Solo tested in Firefox on Windows. When saving, this dialog reports that the source of the file is "blob:"

Tester suggested that if possible the source might be better identified.
![solo-blockly-savefromblob](https://user-images.githubusercontent.com/22827298/61420372-f3d75300-a8b6-11e9-9d19-f7b6a3a12887.png)

**Comment by MatzElectronics** [comment]
Not sure it's possible.   In this case, "blob" refers to Binary Large
OBject, and it is because of how the file is constructed and transferred.
 I'll look into it, but I doubt it can be changed.

**Comment by zfi** [comment]
There might be a more appropriate MIME type available that could clear this. We could also look at configuring the nginx server to support more MIME types.

**Comment by MatzElectronics** [comment]
https://github.com/eligrey/FileSaver.js/issues/101

Looks like this can't be changed.

**Comment by PropGit** [comment]
From those conversations, I'd agree; doesn't look like it's possible to change that behavior directly.

**Comment by Steph-Parallax** [comment]
Well, that's a wrap then! Thanks for looking into it.
