### ISSUE TITLE
Security Error - Failed to construct WebSocket

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#334]
An exception was detected at:
```
Error: SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
  at None (/src/blocklypropclient.js:313:26)
```

```
        var connection = new WebSocket(clientService.url('', 'ws'));

```

This is likely related to #323 because they are both trying to use HTTPS to talk to the Client/Launcher. The call to clientService.url() is incorrectly assuming HTTPS.

**Comment by zfi** [comment]
The browser URL from this error is:
```
https://solo.parallax.com/blocklyc.html?openFile=true
```

**Comment by zfi** [comment]
+1 from a new report today. This looks like it's happening when the user is creating a new project.

**Comment by MatzElectronics** [comment]
Same URL?  it's when they open a project.  That being said - I can't seem to replicate this.  I'll keep trying.  Any details on OS/Browser?

**Comment by MatzElectronics** [comment]
Are we seeing this still now?

**Comment by zfi** [comment]
These stopped happening when I rolled Solo back to 1.4.2, so the issue is still in there. @Steph-Parallax reported intermittent connection issues today, especially bad on the S3 board type.

**Comment by MatzElectronics** [comment]
In solocup?

**Comment by zfi** [comment]
Yes, in SoloCup.

**Comment by MatzElectronics** [comment]
Same error, did Sentry capture anything on it?

**Comment by zfi** [comment]
I didn't receive any new events from Sentry on this today. I'll have to pull a copy of the image from AWS in the morning and verify that Sentry is enabled on the test server. It should be.

**Comment by MatzElectronics** [comment]
Okay, one suggestion would be that if anyone testing starts getting
connection issues,  to switch to the other system (solo<->solocup) and see
if they persist.  That helps us know if it is in the browser or the client.

I'm thinking that this specific error happened because #200 was
"half-deployed" in 1.4.3 initially, but now has the complete refactor

**Comment by PropGit** [comment]
I'll take and implement that suggestion if it happens to me.

I've seen a similar (or maybe same) error that surprised me; however, then realized I was using an old VM with a very old Chrome browser (v54, I believe).  Once I updated Chrome on that system, the error never occurred again.

**Comment by zfi** [comment]
Let's verify that this issue went away with the reconstruction of the Launcher interface in Solo as of v.1.5.0.
