### ISSUE TITLE
Editor canvas code/block toggle enabled for code-only project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#34]
Created a project for Propeller C - code only. When the editor canvas is rendered, the Code/Blocks toggle remains active. If this is really a code-only project, the button is really irrelevant and should probably be hidden.

```
 Board/Device/Project type: Propeller C (code-only)
Created On: Wed Jul 17 2019 22:39:51 GMT-0700 (Pacific Daylight Time)
Last Modified: Wed Jul 17 2019 22:40:29 GMT-0700 (Pacific Daylight Time) 
```

![image](https://user-images.githubusercontent.com/8442260/61432225-8fcb8380-a8e4-11e9-8267-d904835a2283.png)

**Comment by MatzElectronics** [comment]
Easy enough fix, but the larger issue os that PropC editing shouldn't be available on solo until it's also available on production.

**Comment by zfi** [comment]
So our options are to disable it until it's ready for release on both platforms or release it on Solo first. Has the feature been properly vetted?

**Comment by MatzElectronics** [comment]
I'd like to think so...but I'm not sure all agree.   It's been in demo for
ages.  There is not a good open save mechanism on solo/local yet, and code
highlighting doesn't match SimpleIDE, but that's it.

**Comment by zfi** [comment]
Let's disable it until we have time to give it some serious attention.

**Comment by MatzElectronics** [comment]
Done, my last PR does that.  Will need the change in both solo and CDN.

**Comment by zfi** [comment]
I am able to create a code only project, which I think I should not be able to do now. The 'Blocks' button is definitely gone - a good thing. 

@MatzElectronics, When I suggested disabling "it", did you understand that to be the 'Blocks' button or the entire code-only feature?

**Comment by MatzElectronics** [comment]
My latest understanding was to disable/hide the entire code-editing
feature.  It should all be behind the "inDemo" fuse.  You'll have to make
sure the fuse is commented out in the appropriate <meta> tag in your
blocklyc.html file.

**Comment by zfi** [comment]
We're in agreement on the feature. It looks like I missed pulling the last commit that contained the commented-out meta tag. The feature is disabled as a default.

Closing this issue.
