### ISSUE TITLE
Update editor page layout

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#35]
Update layout from tables to div's (minimally), flexbox, or css-grid.  More info to come as options are researched.

**Comment by zfi** [comment]
The CDN PR parallaxinc/blocklyprop-cdn #36 has introduced two new issues:

* Formatting is missing from home page upper left corner.

![2019-07-29_16-34-16](https://user-images.githubusercontent.com/8442260/62089869-7fd66c80-b21f-11e9-974c-66bda697aa48.png)

* The dialog to open an existing project no longer filters on svg files.

**Comment by pjewald** [comment]
Verified that the two issues noted earlier have been corrected with PR #39 and PR parallaxinc/BlocklyProp-cdn#161.
