### ISSUE TITLE
Project file contains XML errors

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#357]
The Description tag near the end of the file is missing the '>' character before the data-createdon element.
```
<text class="bkginfo" x="100%" y="100%" transform="translate(-225,13)"
```

Following that element, the project code element begins with an unterminated element tag, 'blockly/xml'. It is possible that the 'blockly/xml' is simply not supposed to be there. I cannot find any data on what the expected format is. 
```
 ... </text>blockly/xml"><block type="comment" id="_N~|flN0^A)Xi:Wh*=%B" x="-512" y="-353">
```

There is also a potential issue with correcting these errors will break the ability to load older project files.

**Comment by MatzElectronics** [comment]
The first thing mentioned above isn't actually a bug.  The `data-createdon` and `data-lastmodified` markers are attributes to the text tag - not their own tags.

But yes, the second thing mentioned is a bug.  It's caused by fixed-length string splitting, and the xml attributes changed when the core was last updated.

The fix I'll be submitting parses the project as an XML DOM, and looks for the innertext of the XML tag, which will prevent future changes to the `<xml>` tag from breaking this again.

**Comment by zfi** [comment]
Ok, we'll call it not a bug. The attributes are undefined in the namespace. Why are these two data elements treated as attributes when all of the other project metadata are enumerated between <text> tags? 
```
    <text class="bkginfo" x="100%" y="100%" transform="translate(-225,-23)">Device: activity-board</text>
    <text class="bkginfo" x="100%" y="100%" transform="translate(-225,-8)">Description: Modify the Audio/Frequency Out block from horizontal to vertical orientation.</text>
    <text class="bkginfo" x="100%" y="100%" transform="translate(-225,13)" data-createdon="Fri Feb 28 2020 09:52:40 GMT-0800 (Pacific Standard Time)" data-lastmodified="Fri Feb 28 2020 09:53:52 GMT-0800 (Pacific Standard Time)"></text>
```
I actually corrected the paring error in my local dev environment and that is what led me to the second item. The error that caused this was the use of a hard coded number for string length instead of figuring out the actual length of the XML header.

So what is the code block format supposed to look like when it's embedded in the project file?

**Comment by MatzElectronics** [comment]
Can we extend this to include another related issue I'm seeing?  Or should that be a separate issue? 

Larger images are getting clipped when viewed as an SVG.

**Comment by pjewald** [comment]
That's going to be a new issue. It may have a root cause in the patch for this issue, but we should track it separately.
