### ISSUE TITLE
The Load to Ram button is active in S3 project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#363]
It shouldn't be active when an S3 (Scribbler Robot) project is loaded on any platform. The Load to RAM button is active in an S3 project running on a Chromebook AND the BlocklyProp Client / Launcher is not loaded. 

The correct behavior is to disable and remove the Load to RAM button when an S3 project is loaded, without any regard to the Client connection state. The Load to EEPROM button should be visible but disabled if the Client / Launcher is not running and visible and enabled when the Client/Launcher is connected.

**Comment by zfi** [comment]
This issue was partially addressed in PR #362 but failed to hide the Load to RAM button as expected.

**Comment by PropGit** [comment]
Verified on Windows and ChromeOS.

**Comment by pjewald** [comment]
Thank you. Marking this for release.

**Comment by PropGit** [comment]
NOTE: I only tested for visual behavior in relation to the OS and the BP Launcher running/not-running.  I have not tested any downloads or serial communication yet; those should be independent of this issue.

**Comment by pjewald** [comment]
The visual behavior is the only code addresses in this patch. The expected results are targeted only at the button state in the toolbar. The underlying callbacks are unchanged.
