### ISSUE TITLE
Consider changing Project Name when Saved name changes (Solo/Local behavior only)

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#37]
When saving a project in Solo and changing the file name, the file's internal "Project Name" remains unchanged.  This at first doesn't seem bad, but the user workflow may make it odd later... after renaming the blocks file 1 or 2 times upon save.

Perhaps Blockly Prop Solo (and Local) should rename the Project Name to that of the file?

**Comment by MatzElectronics** [comment]
The filename and project name aren't the same thing, so there are two approaches here:

If we can successfully and consistently trap the new file name on a save, we can replace it.  We should, in this case, make sure that users can only name projects in filename-safe ways (limited charset & length).

The other option is to display the filename in addition to the project name...maybe in smaller text below or parenthesis after in the top-right corner.

**Comment by zfi** [comment]
I would like to see the project name and filename remain separate. The BlocklyProp project has no internal representation of filenames. When a user exports a project, use use the project name (or a filesystem-legal representation) to persist the project to storage. Solo and Local are currently doing the same thing. 

As for changing how this works, we need to be consistent. We could add a field to the project.prototype to store the filename if one exists. The application then has the option to use it as needed. It also keeps all of the project-related "stuff" together in a logical bundle.

The UI is going to need a little help here too. We want the user to know the name of the project, possible it's path and filename and I am also asking for the project type to be displayed. So we need to do that it a way that is not cluttered or involve font sizes that seniors cannot read.

**Comment by PropGit** [comment]
Makes sense.  At the moment I'm not sure how to achieve this but I'm looking forward to helping/discovering our direction here.

**Comment by MatzElectronics** [comment]
Issue #106 negates the need for this.
