### ISSUE TITLE
Edit Project Details contains unwanted information

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#38]
Selected Open Project, opened an existing SVG (saved just recently), then selected Edit Project Details.

The Project's Details field contains raw information from the file, rather than text from the user.  In this case, I didn't enter any text at all for the description (for the SVG that I created)... perhaps this only happens when no text has been entered.

**Comment by zfi** [comment]
@PropGit can you please try this again if you have a dev environment or send the svg file to me for testing?

**Comment by PropGit** [comment]
@zfi - Here's one of the svg files that exhibited this problem.  [I2C Test.zip](https://github.com/parallaxinc/solo/files/3477136/I2C.Test.zip)

**Comment by zfi** [comment]
@PropGit, when I load this svg file, the description field is empty. I believe that is the correct behavior. If you agree, I can mark this one resolved.

**Comment by PropGit** [comment]
I agree.  Yes, that description field was supposed to be blank, so it appears the fix solved the problem.
