### ISSUE TITLE
Test for enabled block fails in communication.js file.

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#384]
The code to test for an enabled block contains a misspelling of the property 'disabled in the following object definitions:

* Blockly.propc.oled_initialize
* Blockly.propc.wx_init

For example:
```
Blockly.propc.wx_init = function () {
    if (!this.diabled) {  <<===---
        var pin_di = this.getFieldValue('DI') || '30';
        var pin_do = this.getFieldValue('DO') || '31';
```

**Comment by MatzElectronics** [comment]
![image](https://user-images.githubusercontent.com/19737272/77372084-1a8d3980-6d22-11ea-88a6-f188dc08f462.png)
