### ISSUE TITLE
Solo connects and disconnects randomly

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/solo#391]
@MatzElectronics could you get a look at this video https://drive.google.com/open?id=1zwX8n3yVLslweZJf3towic5ahonwBFAD? 

We have 50 teachers in a class starting Monday. 

Thanks, Ken

**Comment by zfi** [comment]
This issue first appeared in v1.4.2e, released on 3/26/2020.
Failures detected in blocklypropclient.js:establishBPClientConnection(); 

```
$.get(clientService.url(), function (data) {
```

**Comment by zfi** [comment]
Source code for this is in branch solo/hotfix-1.4.2e

**Comment by MatzElectronics** [comment]
Looking now - @zfi is there a stack trace anywhere when you say "Failures detected"?

**Comment by zfi** [comment]
Located a race condition in findClient() that calls a function to open a web socket and then tests the clientService.type, which has not yet been set for success or failure.

Added a one second timer to the code that tests for the result to allow time for the socket to open and report back. Ideally, this needs to be handled differently.

**Comment by zfi** [comment]
Hotfix applied to the master branch and released as Solo 1.4.2.7.
Closing this issue.
