### ISSUE TITLE
Solo loses connection with the launcher

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#394]
Since the latest pull, I've noticed frequent times when Solo loses connection to the launcher. Sometimes it stays connected; sometimes it stays disconnected; sometimes it alternates between connected and disconnected every other second or so. When it disconnects, it defaults to COM1 and stays there. This means that when I'm running a program with a graph or terminal on COM101, say, the communication stops and doesn't come back.

I'm running Solo with Chrome on Win7, but I see the same thing happening with Firefox.

BTW, restarting the launcher doesn't help, nor does restarting the browser.

**Comment by zfi** [comment]
You don't say what branch you pulled from, but the master branch was updated today to address an issue #391 that is very similar to what you are seeing.

**Comment by phil-pilgrim** [comment]
Just tried pulling from parallaxinc/master to my master. Unfortunately, I have conflicts that need to be resolved. No idea how to do that. Would it be bad just to copy and paste from the files that got changed? Or does that screw up the entire system?

**Comment by zfi** [comment]
The merge conflicts happen when you make changes to your master branch that are not reflected in the upstream repository. Depending on the number of conflicts, you can triage them and then commit the resolved files back into the master branch or you can abandon the pull request and start over.  Here is an article that describes the process in some detail if you choose to soldier on and resolve the conflicts. 

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

And here is how to abandon the pull request:
```
git merge --abort
```
And more information about the process:
https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging

**Comment by zfi** [comment]
I just looked at your repository and found that what you are working on was forked from @MatzElectronics repository. You should probably contact him directly about this.
