### ISSUE TITLE
License link switches system context

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#41]
The License link switches the user from the Solo to the Blockly Prop site (replaces current tab) which could lead to user confusion with a number of other links available there (including Login/Register).

Suggest we serve the license page from Solo instead of Blockly Prop (Production).

**Comment by MatzElectronics** [comment]
Once we pull in 155 - it would be very easy to move this info into a modal on the page instead of linking somewhere else.

**Comment by pjewald** [comment]
Do we need 155 to embed the license message in a modal now? Maybe I'm missing an important detail here?

**Comment by MatzElectronics** [comment]
We could do a pure HTML5/CSS/JS modal, but I think it's worth waiting for
jQuery modal.  We could bring it in ahead of 155.

**Comment by zfi** [comment]
The license is now displayed in a modal window on top of the home page. 
Closing this issue.
