### ISSUE TITLE
Serial protocol blocks are not saving correctly when disabled

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/solo#414]
I haven't had enough time to investigate this, so it will need a bit more research, but here is what I suspect is happening.

The Serial protocol blocks rely on the serial protocol init block to provide a set of pins for RX and TX.  If that block is out on the workspace, but disabled, something is going wrong when it's reporting to the other blocks, which is then causing problems when the project is saved/reopened.

**Comment by zfi** [comment]
Following up on this. I tested serial protocol blocks against v.1.5.0-b1 in various combinations of disabled state; saved the project; bailed out to the home page and loaded the altered project. The pin assignments are solid in each case.

**Comment by zfi** [comment]
Closing this issue. Please feel free to reopen it if there is more information available.
