### ISSUE TITLE
Solocup save project before import

### ISSUE THREAD

**Issue by ataylor-parallax** [parallaxinc/solo#425]
In Solocup v1.5.0-b1, when in the editor, clicking the hamburger menu in the top right reveals the import project file button. Clicking this prompts a dialogue box that states that you must save your project before importing, but saving and repeating this process does not yield any difference. Therefore, it seems impossible to import a project as an add on to an existing project.

**Comment by zfi** [comment]
There are at least two issues happening here. The function that detects any changes between the current state of the code and the original state of the code is actually doing it's job and reporting that the two copies of the code are not identical. The reason they are not identical, even after saving the project is that the project code can have two xmlns declarations whereas the code reported back from Blockly contains only one. 

Original project code:
```
<xml xmlns="http://www.w3.org/1999/xhtml"><variables xmlns="https://developers.google.com/blockly/xml"><variable id="}e^ [...]
```

Blockly version of the code:
```
<xml xmlns="https://developers.google.com/blockly/xml"><variables><variable id="}e^`[...]
```

The second issue is that the logic for importing does not permit the import to occur if the current state of the project is not persisted to storage. The Import dialog should present an option to proceed even if the current project is not saved. I would like to get a second opinion on this part before coding it.

**Comment by zfi** [comment]
Moving the first part of this issue to a new issue #427.

**Comment by zfi** [comment]
This specific issue appears to be resolved, but the import function appears to no longer actually do anything after the import dialog has been dismissed.

**Comment by zfi** [comment]
Update in 1.5.0-b6. When a project is modified, Solo now correctly identifies this and will issue a warning dialog when the import menu item is selected from the hamburger menu. The dialog provides options to accept that the changed project will not be saved and an option to discontinue the import and return to the editor canvas.
