### ISSUE TITLE
Custom block fails to load

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#435]
The attached project works in BlocklyProp but fails to load in Solo.

<img width="670" alt="Screen Shot 2020-05-18 at 8 38 26 AM" src="https://user-images.githubusercontent.com/8442260/82232106-ff364900-98e2-11ea-965c-92711f53c36b.png">
[Project60669.svg.zip](https://github.com/parallaxinc/solo/files/4645120/Project60669.svg.zip)

**Comment by pjewald** [comment]
This is the same root issue as #432. Will start tracking it there.
