### ISSUE TITLE
Send "pref-port" message to Launcher when user chooses a port

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#439]
**Background:**
BlocklyProp Launcher v1.0.1 includes enhanced port management to ease the user experience.  This works great, but there's a small uncertainty in the existing systems, Solo included - when the user selects a port from the port list, Launcher doesn't know about it until they choose to download or open a terminal/graph.  

This means - if a user chooses a different port, does some project work, saves, etc. (anything but download/terminal/graph) and then switches projects or exits Solo, upon returning to a project, Launcher makes the previous (not the current) selected port the newly selected port.  This leads to an incorrect port selected (in the mind of the user), or no port selected at all (if the previous selected port doesn't currently exist).

**Enhancement:**
This can be solved if Solo can detect when the user chooses a different port. 

If Solo can detect that event, it can send a new message (as of Launcher v1.0.1) to Launcher:  ```{type: "pref-port", portPath: "user_selected_port"}``` to let Launcher know the user's new preferred port.   ```user_selected_port``` is the text of the selected port item in the port list.  There is a one-way message; Launcher will not respond to a "pref-port" message except to internally take note of the detail and to log it on its log view.

_Important: Do not allow autoselections (like empty port item which is autoselected when port was removed) to trigger this message!  That would cause serious problems._

**Comment by zfi** [comment]
This appears to be a breaking change for SoloDev. Solo thinks that the array of ports sent from the Launcher are all valid port strings. The blank port string appears first, so it isn't obvious what should be happening with the drop-down. 

I am still trying to work out what should be happening with port lists. Solo initiates the request for a port list and a port list is received every few seconds. It appears that , once the list is requested, the Launcher will continue sending a list on a regular interval until the Launcher detects that the web socket has been closed or abandoned.

The port list now contains a blank string. Does this happen when there are no real ports detected? That is, the Launcher will **always** return a port list with at least the empty string entry? Solo depends on an empty list to know if there is a port available and makes adjustments to the button state from that determination. 

I'll address the enhancement portion of this in a bit. First, I need to fix this:

<img width="351" alt="Screen Shot 2020-05-22 at 9 07 26 AM" src="https://user-images.githubusercontent.com/8442260/82687137-c3b1bc80-9c0b-11ea-90b0-031204c6377f.png">

<img width="359" alt="Screen Shot 2020-05-22 at 9 07 37 AM" src="https://user-images.githubusercontent.com/8442260/82687154-c90f0700-9c0b-11ea-8783-5ab644a4ff7f.png">

**Comment by PropGit** [comment]
> This appears to be a breaking change for SoloDev.

It's not behaving like the currently-published SoloCup, Solo, or BlocklyProp when run with BP Launcher v1.0.1?

> Solo thinks that the array of ports sent from the Launcher are all valid port strings. The blank port string appears first, so it isn't obvious what should be happening with the drop-down.

The change should only be in how we interpret it.  The current-published systems work perfectly with this change.  The entries are all valid ports with the exception of a blank port (if it appears).

Launcher will always send an empty list (no items, []) if there are no ports.  This is the same as before.

Launcher will usually send a list with items in each (such as ["COM8"] or ["COM1", "COM14", "wx23854"]); however, occasionally (when the conditions warrant), it will send that list with a blank first entry (such as ["", "COM8"] or ["", "COM1", "COM14", "wx23854"]).  What event warrants it?  Well, when a port was selected, let's say COM14 in this case, and then was removed... instead of the list being ["COM1", "COM14", "wx23854"], as it would be normally, it becomes ["", "COM1", "wx23854"] and SoloDev should do exactly like the others currently do... I think they look in the newly-received list to try to find and select COM14 and upon seeing that it doesn't exist in the new list, it select the first item in the list (which now is "").  That's exactly what we want to happen.

From the user's perspective, they had a port selected, then they disconnected the port and the UI updates their port selection from COM14 to "" and sits there, waiting for the port to arrive again (in which case SoloDev should re-select COM14 from that newly-received list) or the user chooses to select another port.

>  It appears that , once the list is requested, the Launcher will continue sending a list on a regular interval until the Launcher detects that the web socket has been closed or abandoned.

That's correct.

> The port list now contains a blank string. Does this happen when there are no real ports detected?

No.  (See above).

> That is, the Launcher will always return a port list with at least the empty string entry?

No.  Only port list with empty string when there are other ports to choose from, but the user's previously selected port is not there.

> Solo depends on an empty list to know if there is a port available and makes adjustments to the button state from that determination.

Perfect; but this enhancement is requesting the that logic be modified to: if ((empty list) || (selected item === "")) {disable download and terminal/graph buttons} else {enable appropriate buttons}

> First, I need to fix this:

No no... that's exactly as it should be, except the download/terminal/graph buttons should be disabled with the empty item is selected.  This new feature makes the port list a place-holder for a port that disappeared (and may return soon), or a case where the proper port can not be inferred (thus user interaction with the port list is required).

If you want, we could make it "<NONE>" instead of ""; however, the condition you noted in the graphic above did exactly what it was meant to... it triggered you to look at the drop down list and potentially select a different visible port.  That's one of the possibilities we want the users to naturally think to do.

**Comment by PropGit** [comment]
By the way, on that last part, if the user looked at the drop down list and choose a visible port (assuming they've downloaded, or SoloDev sent Launcher a "pref-port" message alerting it to the port change) the next list(s) it will get will be ["cu.usbserial-DN0286UD"] in this case, indicating there's only one port visible and the user's preferred port is that one port... thus, no blank item at the top of the list holding a place for the previous preferred port (which was recently disconnected) or for a port that cannot be inferred from the current state of things.

**Comment by PropGit** [comment]
> The initial port list that Solo received from the Launcher is guaranteed to be either an empty array or an array that contains valid port strings only. 

No, the initial port list can be anything that could occur at any other time as well: an empty array, an array with all valid ports, or an array with a leading blank port followed by valid ports.

> Subsequent messages will be either an empty array or an array of valid port strings 

No, same as above.  At any time, the port list message could be an empty array, an array with all valid ports, or an array with a leading blank port followed by valid ports.

> The Launcher does not declare a default port unless or until the user performs one of the following:
>- Load to RAM / EEPROM
>- Enable a terminal
>- Enable a graph

Not quite, adjusted for truth below:

The Launcher does not declare a default port unless or until the user performs one of the following:
- Load to RAM / EEPROM
- Enable a terminal
- Enable a graph

or, issue #439 is implemented and the user selected another port,
or, Launcher just started running and loaded the last preferred port from Chrome storage.

> At that point, the Launcher will declare the port used as a default port going forward ***until the web socket is closed.*** When the Launcher has made this determination, it will order the detected ports in the port list sent to Solo where the selected port is the first entry. The remaining entries are determinate based on an algorithm chose by the Launcher.  

No, forever.  It stores it in Chrome Storage for convenient retrieval next session.  The rest of the statement is correct.

> The port list will be transmitted to Solo in this order until the user detaches the device connected to the default port. 

...or user selects another port, or a port disappears, or new ports reappear.  The preferred port (if it exists) will always be the first port in the list sent to Solo though.  

If a user chooses another port, the now-selected port stays where it is or will move around the list depending on other port arrivals/departures (unless 439 is implemented or until the user downloads/terminal/graph so that Launcher knows about the new preferred port).

> The port list sent to Solo is modified such that the first entry in the list is a blank (placeholder) entry. 

True, if there's a preferred port (known) that is not currently available. 

> The disconnected port is removed from the list sent to Solo.

Yes.

> The modified port list continues to be sent to Solo until the user connects the missing device. Adding or removing any other devices are noted in the port list but not interesting to the Launcher. 

 
... or the user connects a different wired port; then that becomes the first port in the list (instead of blank) with the intention to be automatically selected (so that the user doesn't have to manually select it)... ie: it's inferred that a newly-connect port should be the port to use unless a preferred port already exists in the list.

> If the user plugs in the missing device, Launcher will remove the blank entry from the port list and replace it with the default device. 

Yes, replaces it with the preferred port.

> Subsequent port lists will contain the port strings identified on the user's system and will no longer contain the empty string until such time as the user disconnects the device again.

Yes.  

> If at any point, the user selects a port from the drop down that is not the default port, Solo will send a 'pref-port' message to Launcher to inform it of the users port choice. Launcher will not provide a reply to this message. Subsequent port lists will be ordered such that the user selection will the first item on the list. If the list contained a blank string prior to receiving the 'pref-port' message, Launcher will update the new default and remove the empty string from the port list. 

Yes.

It sounds more complicated than it is.

When a new port list arrives, Solo only needs to do this:
- If a port item is currently selected
  - remember the port item's text
- else
  - remember "" instead
- Replace the port list with the newly-received list
- Is the new list empty?
  - Done (unless you need to set the selected item to -1 or something)
- else
  - Does the new list contain a port item that matches the remembered port item?
    - Select that port item
  - else
    - Select the 1st port item (whatever it is)

**Comment by PropGit** [comment]
If that above logic (at the end of the post above) doesn't work, or you're concerned about any of it, I'm open to discussion, of course.

**Comment by zfi** [comment]
In the use case where there is only one device connected, the connected device is the only item in the drop down list and it is already selected, the user cannot select the device because is already selected. Since selecting the device is what triggers the preferred_port notification, we will have to find a way to either detect that there is a single port and set it as the preferred port or something else?

**Comment by PropGit** [comment]
That use case shouldn't be a problem because:
- If the old Launcher sent that single-port list, it doesn't care about pref-port messages anyway
- If the new Launcher sent that single-port list, it's because it already knows the port is the preferred port (otherwise it'd send a blank entry followed by the port entry) and is expecting Solo to select that port automatically (because it's the first port in the list)

If you've found a case where that doesn't hold true, I'm not aware of it.

**Comment by zfi** [comment]
Does the Launcher actually persist the single port as the default port? My understanding is the Launcher will not record the default port unless it receives a preferred_port message from Solo. Maybe Solo should care about this in a single port configuration?

**Comment by zfi** [comment]
To clarify from your updated response, when there is just a single port and the Launcher does NOT have a preferred_port designation, Solo does not need to send a preferred_port message. Thanks.

**Comment by PropGit** [comment]
Launcher tries to persist a port as the preferred port in the following cases:
- Solo sends Launcher a pref-port message
- Solo sends a download request with a port listed (which is required, of course)
- Solo sends a communication request (for terminal or graph use) with a port listed (which is required, of course)

Previous BP, Solo, and SoloCup did the bottom two already, but the first is a new feature to improve the session storage behavior.

I said "tries" only because it was recently brought to light that the nwjs-wrapped Launcher can't persist (using chrome.storage API), but that's something I intend to resolve soon.

**Comment by PropGit** [comment]
> To clarify from your updated response, when there is just a single port and the Launcher does NOT have a preferred_port designation, Solo does not need to send a preferred_port message. Thanks.

Yes.  You're welcome.
