### ISSUE TITLE
Prevent "pref-port" message caused by port list refresh

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#444]
As it relates to #439 and as evidenced in the bottom screenshot of [this BP Launcher post](https://github.com/parallaxinc/BlocklyPropLauncher/issues/119#issuecomment-635111376) - Solo needs to prevent sending "pref-port" messages that are triggered by port list refreshes.

It appears from the image in the BP Launcher post that Solo's port changed event is being triggered by the port refresh action rather than by user action.  The "pref-port" messages _should only be sent_ upon an actual user interaction with the port list which causes a port to be selected.

Perhaps the port changed event is agnostic to user vs. program selection of the port.  If that's the case, a one-shot flag needs to be implemented (set by the code that received and processed the port refresh) to indicate to skip the "pref-port" message processing one time (flag is cleared by the "pref-port" message processing code).

**Comment by zfi** [comment]
There was a call to set the preferred port in the message pump. It has been removed.
