### ISSUE TITLE
SD Blocks should not be available to Flip board type

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#473]
The Flip board type does not actually support the SD card blocks, yet that are available in this project type. Please remove them from the Flip /Project Board board type.

**Comment by pjewald** [comment]
Anyone can plug in an SD card interface to the Flip module on a breadboard. The AD blocks can remain in the Flip board type. However, the SD_Init block is missing from this collection and needs to be included.

**Comment by zfi** [comment]
Addressed in release 1.5.2.
Closing.
