### ISSUE TITLE
Can't access Help & Reference from hamburger menu

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/solo#48]
I am able to access the Help menu from right clicking on a block and also from the Solo main page but not from the hamburger menu.

![2019-08-08_09-30-35](https://user-images.githubusercontent.com/20686764/62720597-332d2700-b9bf-11e9-92e3-603d0e5f52dd.png)

**Comment by zfi** [comment]
The help link in the hamburger menu is once again referencing /public/help instead of the link to the landing page of the Learn web site.

**Comment by zfi** [comment]
This error was introduced in PR #36. The correct help URL is "https://learn.parallax.com/ab-blocks" target="_blank"

**Comment by MatzElectronics** [comment]
My bad...we can do this in the CDN/JS, and that way the link is a bit more
dynamic...i.e. if it's a scribbler project, it can point to the scribbler
help instead, and eventually, a propc project can point to the propc help...

**Comment by zfi** [comment]
Verified.
Closing issue.

**Comment by pjewald** [comment]
Adjusting HTML and CDN code to adjust the default URL based upon the project board type.

**Comment by zfi** [comment]
The new code works as expected. 
Closing the issue again.
