### ISSUE TITLE
TypeError: window.getAllUrlParameters is not a function

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#481]
Sentry is reporting an error:
```
TypeError: window.getAllUrlParameters is not a function
  at saveProjectAs (./src/modules/editor.js:792:31)
  at apply (./src/modules/editor.js:359:45)
```

The code is referencing an old global function reference that has been replaced with a method in the utility module.

**Comment by pjewald** [comment]
This issue is addressed in Solo PR #482
