### ISSUE TITLE
Can't save empty project warning

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/solo#49]
Blockly outputs a warning it can't save an empty file however the file is not empty.

![2019-08-08_09-35-18](https://user-images.githubusercontent.com/20686764/62720890-d9792c80-b9bf-11e9-80a1-39ff447d722f.png)

**Comment by zfi** [comment]
@mrodriguez-parallax, Can you provide a brief set of steps you followed to get to this point? If you started with a project file, can you upload it here so we can have a look at it?

**Comment by Steph-Parallax** [comment]
Just happened to me. 
I went to the site,
 I created a new project for the Propeller Flip board type; it included a description. 
I built the project with blocks, but I did not try compiling or loading it. 
I clicked away from the page for a while. I returned to the page and my project was still visible.
 I clicked Save.

**Comment by MatzElectronics** [comment]
I'll try to hop on quick and see what's going on in about 30 min.

**Comment by Steph-Parallax** [comment]
Forgot to add - when I returned to the page it had the "it has been so many minutes...: message. 
That is where I clicked Save.  I have returned to the page to click OK on the "you can't save an empty project!" message, and then I clicked Close on the dialog underneath. I'm left with a greyed out window  that is totally non-responsive.

**Comment by ataylor-parallax** [comment]
I have tested and verified that this is fixed.

**Comment by zfi** [comment]
Thank you. 
Closing this issue.
