### ISSUE TITLE
Refactor HTML Pages for Open and New project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#5]
Refactor the "Open Project" and "New Project" functionality into the editor HTML page. The editor page should handle a query string that either identifies the source of and existing project and load it onto the canvas or provide a dialog for a new project and then present that new project on the editor canvas.

**Comment by zfi** [comment]
Open Project link on the home page opens this dialog:

![2019-07-10_14-11-29](https://user-images.githubusercontent.com/8442260/61005374-ef41f600-a31c-11e9-9fbb-5baafc32c270.png)

Since there is no existing project, can the 'Replace' and 'Append' buttons be supplanted with an 'Open' button? The Cancel button is fine.  Also, since we are just opening a file and not uploading it, can the dialog header text say 'Open blocks file' ?

**Comment by MatzElectronics** [comment]
Yes, I think there are some language constructs here that need to be tweaked.

**Comment by MatzElectronics** [comment]
Opening a new issue for the UI work.  May we close this one?
