### ISSUE TITLE
Mouse pointer changes to edit text bar in hamburger menu

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#50]
![image](https://user-images.githubusercontent.com/22827298/62722729-f6176380-b9c3-11e9-8d95-e42b20f91526.png)

In the Hamburger menu, placing your mouse pointer on the Edit Project Details, Import blocks file, or Confibure client options causes it to change from a pointer to the vertical bar thingy that usually indicates you are in an editable text field. (Sorry, don't know the thingy's proper name).

**Comment by MatzElectronics** [comment]
This happens when the <a> tag doesn't have an href= attribute.  It's easy to override this in css.  I'll submit a fix.

**Comment by zfi** [comment]
That would be an i-beam.

**Comment by zfi** [comment]
Confirmed that this has been corrected.
Closing the issue.
