### ISSUE TITLE
Save Project Reminder is a little overzealous

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#500]
![image](https://user-images.githubusercontent.com/22827298/88853350-6e160500-d1a4-11ea-8c6c-a53ffa38ecf2.png)

This appeared after creating a new project, letting it sit until the Save Project Reminder window came up after a typical many-minute interval then saving the file. The reminder popped up again right away.  Perhaps it isn't clearing some counter after a save, instead of a dismiss?

**Comment by pjewald** [comment]
The timer associated with the current default project is not managed properly when a new project is created. It appears to continue using the timer associated with the default project. It is also not being reset correctly when the current project is saved but not dismissed.

**Comment by zfi** [comment]
Addressed in version 1.5.6.
The Save Project reminder has been disabled while the underlying code gets some much needed attention.

**Comment by Mharrison2020** [comment]
In using Blockly Solo my timer got to the point where the 10 minutes became every 3 minutes.  We do need an edit of preferences to control features like this.
