### ISSUE TITLE
User-defined code block missing from almost all board types

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#501]
The user-defined code block was originally meant to be included with all but the S3.
It has been added to the S3 board type in Solo by recent request.
However it is missing from all the other board types in Solo!
Can we please have the user defined code block added to the rest of the board types?

**Comment by zfi** [comment]
The exclusion for non-S3 projects was introduced in the patch to  include the block in the S3 project type. Oops.

The toolbox has been updated such that the custom code block is available for all board types.
