### ISSUE TITLE
Badge WX Communication > Display blocks missing

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#504]
A customer reports seeing no Communicate > Badge Display blocks.
When tested, I see just one Communicate > Badge Display block, Display print text.  However, I cannot place it on the canvas.
There should be twelve blocks available under Communicate > Badge Display.

**Comment by zfi** [comment]
This is the same root issue as #503. Linking to that issue.

**Comment by Steph-Parallax** [comment]
Oh, even though it is not the same badge board type? Interesting. Thanks!

**Comment by zfi** [comment]
What is the board type where you are seeing this?

**Comment by Steph-Parallax** [comment]
Badge WX, as compared to Hackable Electronic Badge. Not the same animals.

**Comment by zfi** [comment]
Agreed. It has the same underlying issue but with different block aliases.

**Comment by zfi** [comment]
Addressed in Solo 1.5.6
