### ISSUE TITLE
With S3 project, Terminal is opened @ 115200 baud instead of @ 9600 baud

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#510]
For the S3 Robot, terminal communication occurs at 9600 baud; however, Solo's Terminal button (and automatic Terminal after download?) sends a "serial-terminal" request message to BlocklyProp Launcher requesting a baudrate of 115200.

To be clear: The Scribbler Robot (S3) board type is the only one that should be 9600 for all terminal communications.

**Comment by PropGit** [comment]
This appears to be triggering a port lockout situation with Launcher and could explain a recent occurrence of customer issues that require a BP Launcher restart (in its current state) to resolve.

**Comment by PropGit** [comment]
**More Info:**

Once an S3 project is compiled and downloaded to the Propeller containing a Terminal block, the effect is the Terminal opens (says it's connected at 115200 baud) and stays blank; however, for some crazy reason the 9600 baud data that is arriving from the Propeller, on the port which is set to 115200 baud, causes something in Chrome's interface to the port to get very confused (silently) and then when Launcher later so much as tries to twiddle a control signal (ie: DTR to reset the Propeller because the user tried another download in their confused attempt to "fix" the blank terminal situation), the API/OS says "NOPE!  Can't do it."  It doesn't give any reason... just no!.  And the situation doesn't seem to be gracefully recoverable.

**Comment by zfi** [comment]
The baud rate is currently declared as a constant, set to 115200. Ideally, the ClientServices object should manage this setting; set it to a default value of 115200 and provide setter and getter methods to manage the setting. We should also update this setting whenever a project is created or loaded.

**Comment by PropGit** [comment]
To test:
  * Run BP Launcher v1.0.1 or above.
  * Set for Verbose Logging
  * Run Solo
  * Open the attached project (you can use a Propeller Activity Board
  * Download
  * Watch for the baudrate that it opens the terminal at

![image](https://user-images.githubusercontent.com/1266318/93270694-834fee80-f766-11ea-9481-07f54d312db2.png)

  * If it opens at 115200 baud, the terminal will remain blank and the next downloads will fail (the OS will block BP Launcher for configuring the port.
  * If it opens at 9600 baud, the terminal should display text
Once the terminal is opened at 115200 baud and the Propeller sends data at 9600 baud, BP Launcher will be unable to perform more tasks with the port... close and restart BP Launcher to try again.

[Scribbler3-Solo-Fail.zip](https://github.com/parallaxinc/solo/files/5228506/Scribbler3-Solo-Fail.zip)

**Comment by pjewald** [comment]
Updated the ClientServices object to manage the terminal baud rate setting that is defined in each board type. All code paths that either create or load a project will set the terminal baud rate when creating or loading a project.

Release v1.5.5

**Comment by PropGit** [comment]
Further testing reveals that the Terminal isn't the cause of the every-other-download-makes-disconnect issue.  I can download code that doesn't use the terminal and the 2nd time downloading causes Solo to disconnect and reconnect at the point it's trying to download.

**Comment by pjewald** [comment]
Let's create a new issue for this error. The terminal port is now operating at the correct 9600 baud speed.

**Comment by PropGit** [comment]
Here's the Solo Console output for a successful download, then a failed download.

```
11:08:28.248 instrument.js:108 11:08:28.247 Loading program to RAM.
11:08:28.248 instrument.js:108 11:08:28.248 Load connection is active
11:08:28.249 instrument.js:108 11:08:28.249 Ports are available
11:08:28.271 instrument.js:108 11:08:28.271 Requesting compiler service
11:08:28.756 instrument.js:108 11:08:28.756 Receiving compiler service results
11:08:28.756 instrument.js:108 11:08:28.756 Processing cloud compiler callback
11:08:28.757 instrument.js:108 11:08:28.757 Device loaded via websocket
```
That was successful, then I waited about 15 seconds and tried again...
```
11:08:44.423 instrument.js:108 11:08:44.422 Loading program to RAM.
11:08:44.424 instrument.js:108 11:08:44.424 Load connection is active
11:08:44.425 instrument.js:108 11:08:44.424 Ports are available
11:08:44.450 instrument.js:108 11:08:44.449 Requesting compiler service
11:08:44.692 instrument.js:108 11:08:44.692 Receiving compiler service results
11:08:44.692 instrument.js:108 11:08:44.692 Processing cloud compiler callback
11:08:44.692 instrument.js:108 11:08:44.692 Device loaded via websocket
11:08:44.765 instrument.js:108 11:08:44.765 Closing WS: 1006, undefined
11:08:44.766 instrument.js:108 11:08:44.766 Lost WS connection
11:08:44.766 instrument.js:108 11:08:44.766 Closing socket: ReadyState is:
     3
11:08:44.766 instrument.js:108 11:08:44.766 Null-ing the active connection
11:08:45.173 instrument.js:108 11:08:45.173 Finding a client
11:08:45.173 instrument.js:108 11:08:45.173 Connecting to BP Launcher client
11:08:45.173 instrument.js:108 11:08:45.173 In BPLauncherConnection
11:08:45.481 instrument.js:108 11:08:45.481 Connection is: open, URL: ws://localhost:6009/.
11:08:45.481 instrument.js:108 11:08:45.481 Sending "Hello" to client
11:08:45.483 instrument.js:108 11:08:45.483 BlocklyProp Launcher v1.0.1 detected.
11:08:45.483 instrument.js:108 
```

**Comment by PropGit** [comment]
Going on a hunch here... is it possible Solo is silently deciding the websocket is inactive after the download?

NOTE: BP Launcher halts sending port list updates (every 5 seconds) during the download process, the resumes sending port list updates afterward.  Maybe Solo sees the extra delay (that was caused by download) and treats socket as lost, but only acknowledges that upon next download attempt?

I see that I can wait forever after a successful download and the UI never demonstrates a glitch in port list or download button availability (nor shows a pink message) indicating loss of Launcher connection, but the moment I click the download button again, pink message, disabled download, and cleared port list for a moment, then refreshes with the re-connection data.

From the Launcher side, it sees an open connection the whole time, sending port list updates every 5 seconds (except during downloads), until the moment the user requested a 2nd download... then it sees a disconnected socket and a new connection following about 1200 ms later.

**Comment by PropGit** [comment]
> Let's create a new issue for this error. The terminal port is now operating at the correct 9600 baud speed.

Will do.

**Comment by PropGit** [comment]
This issue is considered tested and closed: Solo now opens Terminal at 9600 baud after download to S3 robot.
