### ISSUE TITLE
Terminal print block and modulus remainder division

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/solo#521]
sample code attached (remove .txt suffix). 

Open code file and observe the code window. 
The code output to terminal has double %%. The code output to item has single %.

![2021-01-11 14_21_15-BlocklyProp Solo](https://user-images.githubusercontent.com/11635798/104187955-d25a1780-5418-11eb-8bfb-cbb2bddd7121.png)

[BlocklyModulusBug.svg.txt](https://github.com/parallaxinc/solo/files/5795968/BlocklyModulusBug.svg.txt)

**Comment by zfi** [comment]
I found a regex that was scanning for a single '%' and replacing it with a '%%'. I don't know why that was in there but it's likely a copy and paste operation from another block.

This update will appear in the 1.5.7 release.
