### ISSUE TITLE
BlocklyProp-Client instruction steps not appearing

### ISSUE THREAD

**Issue by ataylor-parallax** [parallaxinc/solo#53]
![F89D6EB4-51AB-40F1-9A7F-304F27D85343](https://user-images.githubusercontent.com/53913268/62725975-08e16680-b9cb-11e9-97ad-12a601e02e48.GIF)

Upon opening a new instance of solo, I clicked the red text at the to that reads " BlocklyProp-Client not found. Click here for instructions." After clicking it the image for step 1 appears, but if you click over to step 2 or 3 then no image appears. Even if you click back to step 1 there is no image. Closing the box and re-clicking the red text does not resolve the issue, no image appears for any of the steps.

**Comment by ataylor-parallax** [comment]
This issue occurs for both the windows and chrome OS that can be selected at the bottom. For Mac OS it jumps straight to step 4 when you click any of the steps, and you cannot leave step 4. The step that you ckish has a shadow around it, but step 4 is completely blue.

**Comment by ataylor-parallax** [comment]
I have tested this and verified that it is fixed.

**Comment by zfi** [comment]
Thanks!
Closing the issue.
