### ISSUE TITLE
SD file write feature request

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#536]
SD file <write> [4] bytes of (item) block emits fwrite(item, 1, 4, fp);  This is fine when item is a character array.  If item is an int, unexpected results occur.  If I remember correctly, there is no functional difference between frwite(&item... and fwrite(item when it's a character array.  However, if item is an int, then fwrite(&item will work, but frwite(item will not.

If we can safely always precede the variable name in the first argument of frwite with an ampersand, then it would allow the BlocklyProp programmer to use either character arrays or int variables.  This could be very beneficial, and probably much easier than making the block that detect if the variable was declared to be a char[] or an int.

**Comment by zfi** [comment]
I will add the ampersand to the emitted code, but please understand that internally, the SD blocks are designed to only work with character data. Using the blocks with other data types may work but it's up to the user to address any anomalies that come from using those unsupported data types.

**Comment by AndyLindsay** [comment]
Acknowledged.  We will add warnings to the block documentation.

**Comment by AndyLindsay** [comment]
P.S. It might be worth offering binary file options like fopen(..."wb"), fopen(..., "rb"), etc...  There's already some discussion on fopen in #529, so I'll add to that one.
