### ISSUE TITLE
Remove code supporting the BlocklyProp Client app

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#571]
Remove UI elements and underlying code that was supporting the deprecated BlocklyProp Client application.

## Tasks

- [x] Remove UI elements - BP Client download links and buttons
- [x] Remove supporting code in the findClient and supporting functions.

**Comment by zfi** [comment]
UI elements removed in release 1.5.8.

**Comment by zfi** [comment]
Added commits for code targeted for removal as commented out lines and again when the commented out code was removed.

**Comment by zfi** [comment]
Work on this issue is complete in PR #580
