### ISSUE TITLE
Block for opening terminal connection is missing

### ISSUE THREAD

**Issue by Gaeta** [parallaxinc/solo#611]
We have a terminal close connection block but we need a terminal open block

https://learn.parallax.com/tutorials/language/propeller-c/multicore-approaches/print-different-core

requires a simpleterm_open() function in a different core to open a terminal... Yet we cant in it as we dont have a block to do this... 

Simple fix:

Copy the code for a close terminal block and change it so we have a open terminal...

**Comment by zfi** [comment]
The example referenced is for the SimpleIDE tool, not Solo. Solo manages a single terminal session in the project. You should be able to close the terminal with a Terminal Close block and then execute one or more Terminal blocks that will reopen the terminal. Solo does not directly support opening additional terminal windows on other cogs.

We accept pull requests if you have this working.

**Comment by zfi** [comment]
No further discussion. Closing this request.
