### ISSUE TITLE
When on empty project, going home and creating new project: Undefined

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#71]
In 1.3.475
Open existing project
Delete blocks
Try to compile - can't compile empty project box - good
Try to save - can't save an empty project box - good
Nav away from project for a bit.
Go back to project pane, hit Home in upper left.
From Home page, click Create new project
>>The New project dialog does not open - the Home page just flickers.
>>Click Create new project again. New project dialog opens, but you can see the Edit pane grayed out with the project name (undefined) in the upper left.
Window.localStorage = 0

**Comment by zfi** [comment]
I ran through the sequence in an attempt to replicate the error but was unable to break the app. This may have been caused by the conflagration in the code base that was being addressed at about the same time this issue was reported.

Let's get a second opinion before closing this issue.

**Comment by Steph-Parallax** [comment]
I've done a hard cache-clear in Chrome Settings. I will give it a go.

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-624-8333
www.parallax.com
learn.parallax.com

**Comment by Steph-Parallax** [comment]
Verified, with all methods mentioned above.
