### ISSUE TITLE
Unable to compile S3 projects

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#74]
Compiling any S3 program fails with a generic server 500 error message. Project for all other board type appear to compile without incident.

**Comment by ataylor-parallax** [comment]
I just tested this in v1.3.477 and I was able to reproduce it

**Comment by zfi** [comment]
Can you attach the project svg file so we can test it on a dev box? We need to find the root cause for the intermittent performance on S3 projects.

**Comment by MatzElectronics** [comment]
Check the C libraries.  I used a custom block in a ActivityBoard project to
invoke #include "s3.h", and that caused it to generate the error...

**Comment by zfi** [comment]
I'm sorry but I am not connecting the dots here. This issue only occurs with S3 board type. All other board types, including the Activity Board, do not exhibit this error. What exactly is it that we are looking for in the C libraries?

**Comment by MatzElectronics** [comment]
Start with a new Activity Board project.  Add any block to make a project
that compiles to test it.  Then, add a custom code block.  In the includes
field, add:

#include "s3.h"

Try compiling again.

**Comment by zfi** [comment]
The issue as reported is discussing S3 board type projects, not Activity Board projects.

Still, I followed the steps you outlined and this project compiles without error. 
![2019-08-29_09-26-00](https://user-images.githubusercontent.com/8442260/63958377-15dbfd80-ca3f-11e9-9de0-2cefffa9c727.png)


```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "s3.h"



// ------ Main Program ------
int main() {


  // Comment

}


[Activity-S3.svg.zip](https://github.com/parallaxinc/solo/files/3556537/Activity-S3.svg.zip)

**Comment by MatzElectronics** [comment]
![image](https://user-images.githubusercontent.com/19737272/63959246-9f3fff80-ca40-11e9-8421-5bea63bdb868.png)

Huh.  I tried this because I was trying to isolate the problem by adding only one piece to the code at a time.  The s3 type adds a few different things automatically, so by choosing the ActivityBoard type, it allows you to test smaller pieces.

**Comment by zfi** [comment]
Which system are you using when you see this error? For example, the svg file runs without error on my dev system but not on production Solo. To be transparent, I have been working to clean up the code on the compiler system and may have inadvertently corrected whatever is triggering the 500 error. 

It would also be helpful to know exactly what is being sent to the compiler server. The URL including any query strings, and the request body.

**Comment by MatzElectronics** [comment]
Sllo and my local dev

**Comment by zfi** [comment]
The problem appears to the in the S3 header file.

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1018: ordinal not in range(128)
```

**Comment by zfi** [comment]
I don't see anything in the s3.h file that might trigger the decode. I am deploying an update to the cloud compiler that will provide more details in this area of the code.

**Comment by zfi** [comment]
I can confirm that the issue is in Simple Libraries. Version 1.4.122 does not exhibit the issue. Version 1.4.131 does exhibit the issue. I have an older version of the library on my dev system, which is why it was working there and not in the production system.

I am going to open an issue over in the Simple Libraries repo and leave this issue open until it is resolved.

**Comment by MatzElectronics** [comment]
Strange.  As far as I know, the s3 library has not been changed.  Is it
possible that the file is corrupted?   If so, a recompile should just fix
it.  Or just replace the .a and .h with the previous version...

**Comment by zfi** [comment]
The file open function in Python 3 is, as a default, quite strict about the characters it will accept when the file is open in it's default text mode. This same code worked successfully in Python 2.7. A more complete explanation is available in the parallaxinc/simple-libraries#200 issue. 

I updated the code in the cloud compiler to accept the full Latin-1 character set and it now is able to parse the s3.h file successfully.

**Comment by Steph-Parallax** [comment]
In 1.3.477, I can verify that S3 programs compile with one exception: the [factory reset/restore S3 demo block](http://learn.parallax.com/support/reference/scribbler-3-robot-block-reference/actions/reset) returns this error:

Compile... Aw snap. A server error 500 has been detected.

This may in fact be a separate issue, if the error is actually a missing binary called in the generated C code:

// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "s3.h"
#pragma load_default_scribbler_binary


// ------ Main Program ------
int main() {
  s3_setup();
  pause(100);

}

**Comment by zfi** [comment]
I am not able to reproduce this error on Solo or in my dev environment. The compiler reports that the binary was successfully delivered to the client browser. Perhaps I need to actually have an S3 plugged in first?

**Comment by zfi** [comment]
I found an event in the compiler logs that indicates that the demo init binary is not getting bundled into the Docker container. I'm investigating that now.

**Comment by zfi** [comment]
I updated the Cloud Compiler to include the missing S3 demo initialization binary. I'm not sure how that was omitted initially.

Can someone in possession of an S3 retry the demo init routine to verify that this works as expected now?

**Comment by Steph-Parallax** [comment]
Hard-cleared my Chrome cache, restarted my computer, and re-tested with actual S3 connected to my reawakened computer: 

- I can compile and load regular projects.
- I can Verify Code (checkmark button) a project with just the Restore block in it.
- I **cannot** Load and Run (downward arrow button) with just the Restore block in it.   I get this result:

![image](https://user-images.githubusercontent.com/22827298/64280087-3dcad580-cf05-11e9-80b2-96ea057cab49.png)

So while the presence of that binary is necessary of course, there is still something else afoot.

**Comment by zfi** [comment]
Thanks for that feedback. Once the binary was made available, the compiler had an issue in converting the binary file to a json object. This is another artifact of migrating from Python2 to 3. The latest version of the compiler (v1.3.7) addresses this error.

Let's test this again and verify that I have it right this time.

**Comment by Steph-Parallax** [comment]
That did the trick! Restore block is working now also.
