### ISSUE TITLE
Persistent previous project if creating New Project from Hamburger menu only

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/solo#77]
Observed in 1.3.477

- Open Solo
- Create a new project (See-Circle)
- Save project (or not, bug happens either way)
- From within edit pane, choose New Project from hamburger menu
- Fill out Project Details info (Restore-S3)
- Click Continue
- See the "Leave site" dialog (created by Chrome I think) and dismiss it, twice.
- Dialogs go away, and I'm still seeing the blocks and details for See-Circle.  

This is similar to #67 but not identical.  From this point, if I click the upper-left icon and go to Home, I can click on New project from the menu bar and successfully create a new project.

**Comment by zfi** [comment]
The control to create a new project is now a button on the button bar. The 'New' menu item no longer exists.

With the exception noted above, the test procedure works as described.
Closing this issue.
