### ISSUE TITLE
Editor canvas XML button should be disabled

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#8]
The editor canvas Code/Blocks button is also showing an 'XML' mode. The XML mode is a debugging tool and should be disabled as a default. This also means that there will need to be a way to enabled it when it is needed, possibly with a specific query string setting.

![2019-07-10_14-22-31](https://user-images.githubusercontent.com/8442260/61006078-4e543a80-a31e-11e9-9046-a254f4df04fa.png)

**Comment by MatzElectronics** [comment]
This is behind a URL parameter trigger, but it's also triggered by the offline app.  We need to establish what "modes" we want to support, but this is an easy fix in the CDN.

**Comment by zfi** [comment]
We definitely would want a 'debug' mode that is separate from all of the other configuration. A query parameter would be fine to toggle the feature on as needed. This would be easier if there was a class that managed the submitted query string. We add that to the refactoring initiative to come. For the alpha release, can you either disable the XML button or parameterize it if that is easy to implement?
