### ISSUE TITLE
Remove unused source files

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#85]
Please verify that the following files are not required for the Solo project and remove them. Post comments in this issue for questions or clarifications.

* blocklyprophelp.js
* blocklyprophelp.css
* localcompile.js
* oauth-complete.js
* profile.js
* project.js
* projectcreation.js

**Comment by pjewald** [comment]
Adding /src/README.md to the list. This file is empty.

**Comment by zfi** [comment]
Added ace package support files back into the project. These can be pruned at a later date or incorporated into a single minified ace package.

**Comment by zfi** [comment]
Closing this issue.
