### ISSUE TITLE
Editor canvas BlocklyProp hotspot link incorrect

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#9]
On the editor canvas page, clicking on the 'P' image does not return to the home page. Instead, it appears to reload the current editor page with the current project.

![2019-07-10_14-27-06](https://user-images.githubusercontent.com/8442260/61006366-fec23e80-a31e-11e9-8e8c-793d54f2da87.png)

The expected behavior is for the browser to be redirected to the home page.

**Comment by zfi** [comment]
Bumping this issue. @MatzElectronics, let me know if have not started this one and I'll reassign it to me.

**Comment by MatzElectronics** [comment]
Same, I have not.
