### ISSUE TITLE
It has been minutes since you saved your project

### ISSUE THREAD

**Issue by ataylor-parallax** [parallaxinc/solo#92]
When a solo page gets the popup that "It has been ___ minutes since you last saved your project, i does not say the number of minutes that it has been. I'm not sure if this is intentional, but if it is another wording may be better, something along the lines of "It's been awhile since you've saved your project." Here's a snip of what it looks like now:
![image](https://user-images.githubusercontent.com/53913268/65077098-1d603980-d94f-11e9-9ee2-8290fd52ab30.png)

**Comment by zfi** [comment]
This issue is addressed in release 1.3.489. Ready for verification.

**Comment by pjewald** [comment]
Verified. Closing.
