### ISSUE TITLE
Make best effort attempt to identify the correct BP Client installer package

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#95]
Based on feedback from a recent instructor-led class, there was some difficulty in determining which of the Windows BlocklyProp Client installers to use (32 vs 64 bit). A request was made to have the application figure this out and then prompt the user for the best match.

**Comment by PropGit** [comment]
Do we have any evidence (face-to-face or otherwise) that anyone is using 32-bit computers for BlocklyProp?

**Comment by zfi** [comment]
I do not have any evidence that the 32-bit installer is being downloaded or used. But this has not been a monitored metric, so it's also accurate to say we don't know if it is still being used. 

There are 32 bit versions of Windows 8, 8.1 and 10 out there, although Microsoft reports that they represent less than 10% of the deployed Windows systems.

**Comment by zfi** [comment]
Following up on this issue. The new BlocklyProp Launcher is replacing the older BlocklyProp Clients. Solo is now able to query the client (Launcher or BlocklyProp Client) to determine whether the running client is a current version. If it is now, the UI now alerts the user to this and offers a link to the current client release.

Closing this issue.
