### ISSUE TITLE
Add New and Open project buttons to editor toolbar

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#97]
Add buttons on the editor toolbar to support the ability to create a new project or to open an existing project without leaving the editor page.

Move the serial port selector drop-down to the right of the row of state icons on the left side of the toolbar.

Possible replace the Code/Blocks/XML button with icons. Placement and functionality to be determined.

**Comment by Steph-Parallax** [comment]
When in an edit pane, after changing a project, the New and Open buttons give different responses. The New gives a modal, Open gives a Chrome alert.

**Comment by Steph-Parallax** [comment]
Open Solo.
Open a project, did not click in pane or change anything.
From in the Edit pane, click Open again, URL now says solo.paralllax.com/blocklyc.html?openFile=true.  If I hit Cancel, I am back on the home page. I didn't expect this.

**Comment by Steph-Parallax** [comment]
Open a project, but do not click in it.
Hit New button.  It says I have modified the project and offers to save it, but I have not actually even clicked in the pane?

**Comment by MatzElectronics** [comment]
@Steph-Parallax your last find, where it seems to struggle to detect whether you've edited a project and the previous one, where the nav isn't behaving as expected are both issues that were likely present when these options were in the hamburger menu - adding the buttons didn't create them.  They do need to be addressed, but I'd like to reference this in issue #110 and close this one, as the goal of moving the menu items to individual buttons has been addressed and verified.

**Comment by zfi** [comment]
@Steph-Parallax wrote:
> When in an edit pane, after changing a project, the New and Open buttons give different responses. The New gives a modal, Open gives a Chrome alert.

This is confirmed and is not the expected behavior. Both buttons should trigger a bootstrap modal dialog to alert the user that the current project has been modified and has not been saved to disk. 
We need to replace the alert with a modal.

**Comment by zfi** [comment]
With reference to the issues related to Opening a new project and clicking outside of the dialog, the modal now ignores mouse clicks that occur outside of the modal dialog. It should now not be possible to click on the other controls as outlined in the reported error procedures noted above.

**Comment by zfi** [comment]
Moving the variable dialogs issue to a new repo issue, #211.

The original task was to create the New and Open buttons. That work has been done.
Closing this issue.
