### ISSUE TITLE
Continue button vs. Enter key: How the New Project dialog responds to incomplete info

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#99]
In the New Project dialog, if the Continue button is clicked before selecting the board type, a message appears with instructions to select board type before continuing.  If the user instead hits the Enter key, solo goes back to the most recent project without making any changes or explaining that there wasn't enough info.  For incomplete info in the New Project dialog,  I would suggest making the response to Enter the same as it is for the Continue button.

**Comment by zfi** [comment]
The <Enter> key is a vector to closing the modal dialog and is currently bypassing the validation present in the handler for the Continue button. Adding code to trap this vector.

**Comment by zfi** [comment]
Form processing withing Bootstrap does not natively handle the enter key in the way we would like it to. The  solution appears to be trapping the enter key event at the modal dialog level. In the event handler, we can validate the form data and, if valid, send the user back to the editor canvas with the new project ready to roll.

This means the pressing the Continue button or pressing the enter key will now behave exactly the same.

**Comment by zfi** [comment]
...except when the user is entering data in the description. The enter key must not be trapped this specific case.

**Comment by zfi** [comment]
This may actually be an issue in any modal dialog that contains a form. I will submit code for the Edit Project dialog shortly.

**Comment by zfi** [comment]
The Enter key the Continue button event handlers now correctly handle data validation before closing the New Project dialog.

Closing the issue.
